/* ============================================================
   Lectio-Intelligo — Question Bank
   ------------------------------------------------------------
   Each question:
     src     : source id (a Bible book or Catechism part)
     type    : "conceptual" | "fill"  (fill-in-the-blank)
     q       : question text ("____" marks the blank for fill)
     choices : array of 4 options; the FIRST one is correct
               (the app shuffles them at runtime)
     ref     : citation shown with the feedback
   ============================================================ */

const SOURCE_GROUPS = [
  {
    name: "The Pentateuch",
    kind: "bible",
    items: ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"],
  },
  {
    name: "Historical Books",
    kind: "bible",
    items: ["Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings",
            "2 Kings", "Tobit", "Judith", "Esther", "1 Maccabees", "2 Maccabees"],
  },
  {
    name: "Wisdom Books",
    kind: "bible",
    items: ["Job", "Psalms", "Proverbs", "Ecclesiastes", "Wisdom", "Sirach"],
  },
  {
    name: "The Prophets",
    kind: "bible",
    items: ["Isaiah", "Jeremiah", "Ezekiel", "Daniel", "Jonah"],
  },
  {
    name: "The Gospels & Acts",
    kind: "bible",
    items: ["Matthew", "Mark", "Luke", "John", "Acts"],
  },
  {
    name: "Epistles & Revelation",
    kind: "bible",
    items: ["Romans", "1 Corinthians", "Ephesians", "Hebrews", "James", "Revelation"],
  },
  {
    name: "Catechism of the Catholic Church",
    kind: "ccc",
    items: [
      "CCC Part I: The Profession of Faith",
      "CCC Part II: The Sacraments",
      "CCC Part III: Life in Christ",
      "CCC Part IV: Christian Prayer",
    ],
  },
];

const QUESTION_BANK = [

  /* ---------------- Genesis ---------------- */
  { src: "Genesis", type: "fill",
    q: "“In the beginning God created the heavens and the ____.”",
    choices: ["earth", "seas", "angels", "light"],
    ref: "Genesis 1:1" },
  { src: "Genesis", type: "conceptual",
    q: "On which day of creation did God create man?",
    choices: ["The sixth day", "The first day", "The third day", "The seventh day"],
    ref: "Genesis 1:26–31" },
  { src: "Genesis", type: "conceptual",
    q: "What sign did God give Noah as a pledge of His covenant never again to destroy the earth by flood?",
    choices: ["A rainbow", "A dove", "An olive branch", "A pillar of fire"],
    ref: "Genesis 9:12–13" },
  { src: "Genesis", type: "conceptual",
    q: "Which son of Jacob was sold into slavery in Egypt by his brothers?",
    choices: ["Joseph", "Benjamin", "Reuben", "Judah"],
    ref: "Genesis 37:28" },
  { src: "Genesis", type: "fill",
    q: "The serpent tempted Eve, saying: “You will be like God, knowing good and ____.”",
    choices: ["evil", "wisdom", "truth", "life"],
    ref: "Genesis 3:5" },

  /* ---------------- Exodus ---------------- */
  { src: "Exodus", type: "conceptual",
    q: "From what did God first speak to Moses in the wilderness?",
    choices: ["A burning bush", "A whirlwind", "A pillar of cloud", "A still small voice"],
    ref: "Exodus 3:2–4" },
  { src: "Exodus", type: "fill",
    q: "When Moses asked God His name, God replied: “I AM WHO ____.”",
    choices: ["I AM", "I WILL BE", "IS HOLY", "SENT YOU"],
    ref: "Exodus 3:14" },
  { src: "Exodus", type: "conceptual",
    q: "How many plagues did God send upon Egypt?",
    choices: ["Ten", "Seven", "Twelve", "Forty"],
    ref: "Exodus 7–12" },
  { src: "Exodus", type: "conceptual",
    q: "Which feast commemorates Israel's deliverance, when the destroyer passed over houses marked with the blood of a lamb?",
    choices: ["Passover", "Pentecost", "Tabernacles", "Purim"],
    ref: "Exodus 12:21–27" },
  { src: "Exodus", type: "conceptual",
    q: "On which mountain did Moses receive the Ten Commandments?",
    choices: ["Mount Sinai", "Mount Nebo", "Mount Carmel", "Mount Moriah"],
    ref: "Exodus 19–20" },

  /* ---------------- Leviticus ---------------- */
  { src: "Leviticus", type: "fill",
    q: "“You shall be holy; for I the LORD your God am ____.”",
    choices: ["holy", "mighty", "one", "jealous"],
    ref: "Leviticus 19:2" },
  { src: "Leviticus", type: "conceptual",
    q: "From which tribe of Israel did the priests come?",
    choices: ["Levi", "Judah", "Benjamin", "Ephraim"],
    ref: "Leviticus 8; Numbers 3" },
  { src: "Leviticus", type: "fill",
    q: "“You shall love your neighbor as ____.” — a command Jesus later calls the second greatest.",
    choices: ["yourself", "your brother", "the LORD", "your own soul"],
    ref: "Leviticus 19:18" },

  /* ---------------- Numbers ---------------- */
  { src: "Numbers", type: "conceptual",
    q: "What did Moses lift up on a pole so that those bitten by serpents might look at it and live?",
    choices: ["A bronze serpent", "The ark of the covenant", "A golden calf", "Aaron's staff"],
    ref: "Numbers 21:8–9" },
  { src: "Numbers", type: "conceptual",
    q: "For how many years did Israel wander in the wilderness?",
    choices: ["Forty", "Seven", "Twelve", "Seventy"],
    ref: "Numbers 14:33–34" },
  { src: "Numbers", type: "fill",
    q: "The priestly blessing: “The LORD bless you and ____ you.”",
    choices: ["keep", "guide", "heal", "strengthen"],
    ref: "Numbers 6:24" },

  /* ---------------- Deuteronomy ---------------- */
  { src: "Deuteronomy", type: "fill",
    q: "The Shema: “Hear, O Israel: The LORD our God, the LORD is ____.”",
    choices: ["one", "holy", "king", "near"],
    ref: "Deuteronomy 6:4" },
  { src: "Deuteronomy", type: "conceptual",
    q: "What does the name “Deuteronomy” mean?",
    choices: ["Second law", "Book of numbers", "Words of Moses", "The covenant"],
    ref: "Deuteronomy 17:18 (Greek deuteronomion)" },
  { src: "Deuteronomy", type: "fill",
    q: "“Man does not live by ____ alone, but by every word that proceeds out of the mouth of the LORD.”",
    choices: ["bread", "water", "wine", "manna"],
    ref: "Deuteronomy 8:3" },
  { src: "Deuteronomy", type: "conceptual",
    q: "From which mountain did Moses view the Promised Land before he died?",
    choices: ["Mount Nebo", "Mount Sinai", "Mount Horeb", "Mount Tabor"],
    ref: "Deuteronomy 34:1–5" },

  /* ---------------- Joshua ---------------- */
  { src: "Joshua", type: "conceptual",
    q: "The walls of which city fell after Israel marched around it for seven days?",
    choices: ["Jericho", "Ai", "Hebron", "Gibeon"],
    ref: "Joshua 6" },
  { src: "Joshua", type: "fill",
    q: "“As for me and my house, we will serve the ____.”",
    choices: ["LORD", "covenant", "law", "God of Abraham"],
    ref: "Joshua 24:15" },
  { src: "Joshua", type: "conceptual",
    q: "What body of water parted so Israel could cross into the Promised Land?",
    choices: ["The Jordan River", "The Red Sea", "The Sea of Galilee", "The Euphrates"],
    ref: "Joshua 3:14–17" },

  /* ---------------- Judges ---------------- */
  { src: "Judges", type: "conceptual",
    q: "Which judge's great strength was tied to his uncut hair?",
    choices: ["Samson", "Gideon", "Jephthah", "Ehud"],
    ref: "Judges 16:17" },
  { src: "Judges", type: "conceptual",
    q: "Who was the prophetess who judged Israel and accompanied Barak into battle?",
    choices: ["Deborah", "Jael", "Miriam", "Huldah"],
    ref: "Judges 4:4–9" },
  { src: "Judges", type: "conceptual",
    q: "With how many men did Gideon defeat the Midianites?",
    choices: ["Three hundred", "Three thousand", "Twelve hundred", "Seventy"],
    ref: "Judges 7:7" },

  /* ---------------- Ruth ---------------- */
  { src: "Ruth", type: "conceptual",
    q: "Who was Ruth's mother-in-law, whom she refused to abandon?",
    choices: ["Naomi", "Orpah", "Rachel", "Hannah"],
    ref: "Ruth 1:14–16" },
  { src: "Ruth", type: "fill",
    q: "“Where you go I will go… your people shall be my people, and your God my ____.”",
    choices: ["God", "refuge", "portion", "King"],
    ref: "Ruth 1:16" },
  { src: "Ruth", type: "conceptual",
    q: "Ruth married Boaz and became the great-grandmother of which king?",
    choices: ["David", "Saul", "Solomon", "Hezekiah"],
    ref: "Ruth 4:17" },

  /* ---------------- 1 Samuel ---------------- */
  { src: "1 Samuel", type: "fill",
    q: "Young Samuel answered the LORD's call: “Speak, for your servant ____.”",
    choices: ["hears", "waits", "believes", "obeys"],
    ref: "1 Samuel 3:10" },
  { src: "1 Samuel", type: "conceptual",
    q: "What weapon did David use to strike down Goliath?",
    choices: ["A sling and a stone", "A sword", "A spear", "A bow and arrow"],
    ref: "1 Samuel 17:49–50" },
  { src: "1 Samuel", type: "conceptual",
    q: "Who anointed both Saul and David as kings of Israel?",
    choices: ["Samuel", "Nathan", "Eli", "Elijah"],
    ref: "1 Samuel 10:1; 16:13" },

  /* ---------------- 2 Samuel ---------------- */
  { src: "2 Samuel", type: "conceptual",
    q: "Which prophet confronted David over his sin with Bathsheba, saying “You are the man”?",
    choices: ["Nathan", "Samuel", "Gad", "Elisha"],
    ref: "2 Samuel 12:7" },
  { src: "2 Samuel", type: "conceptual",
    q: "What did David bring up to Jerusalem, dancing before the LORD with all his might?",
    choices: ["The ark of the covenant", "The tablets of the law", "The temple treasures", "The bronze serpent"],
    ref: "2 Samuel 6:14–15" },
  { src: "2 Samuel", type: "conceptual",
    q: "Which son of David led a rebellion against him and died caught in a tree?",
    choices: ["Absalom", "Amnon", "Adonijah", "Solomon"],
    ref: "2 Samuel 15; 18:9–15" },

  /* ---------------- 1 Kings ---------------- */
  { src: "1 Kings", type: "conceptual",
    q: "When God offered Solomon anything he wished, what did Solomon ask for?",
    choices: ["Wisdom (an understanding mind)", "Long life", "Riches", "Victory over his enemies"],
    ref: "1 Kings 3:5–9" },
  { src: "1 Kings", type: "conceptual",
    q: "Which prophet challenged the prophets of Baal to a contest on Mount Carmel?",
    choices: ["Elijah", "Elisha", "Isaiah", "Micaiah"],
    ref: "1 Kings 18:20–40" },
  { src: "1 Kings", type: "conceptual",
    q: "What great work did Solomon build in Jerusalem?",
    choices: ["The Temple of the LORD", "The city walls", "The tower of David", "The pools of Siloam"],
    ref: "1 Kings 6" },

  /* ---------------- 2 Kings ---------------- */
  { src: "2 Kings", type: "conceptual",
    q: "How was the prophet Elijah taken up into heaven?",
    choices: ["In a whirlwind, with a chariot of fire", "On the wings of angels", "In his sleep", "From the top of Mount Carmel in a cloud"],
    ref: "2 Kings 2:11" },
  { src: "2 Kings", type: "conceptual",
    q: "Naaman the Syrian was cleansed of leprosy by washing seven times in which river?",
    choices: ["The Jordan", "The Nile", "The Abana", "The Euphrates"],
    ref: "2 Kings 5:10–14" },
  { src: "2 Kings", type: "conceptual",
    q: "Which empire destroyed Jerusalem and the Temple and carried Judah into exile?",
    choices: ["Babylon", "Assyria", "Persia", "Egypt"],
    ref: "2 Kings 25" },

  /* ---------------- Tobit ---------------- */
  { src: "Tobit", type: "conceptual",
    q: "Which archangel, disguised as a traveler, accompanied young Tobias on his journey?",
    choices: ["Raphael", "Michael", "Gabriel", "Uriel"],
    ref: "Tobit 5:4; 12:15" },
  { src: "Tobit", type: "conceptual",
    q: "What remedy healed Tobit's blindness?",
    choices: ["The gall of a fish", "Water from the Jordan", "Oil blessed by a priest", "The touch of an angel's hand"],
    ref: "Tobit 11:7–13" },
  { src: "Tobit", type: "conceptual",
    q: "Whom did Tobias marry, after a demon had slain her seven previous bridegrooms?",
    choices: ["Sarah", "Anna", "Edna", "Susanna"],
    ref: "Tobit 3:7–8; 7:11–13" },

  /* ---------------- Judith ---------------- */
  { src: "Judith", type: "conceptual",
    q: "Judith delivered Israel by beheading which enemy general?",
    choices: ["Holofernes", "Sennacherib", "Nicanor", "Sisera"],
    ref: "Judith 13:6–10" },
  { src: "Judith", type: "conceptual",
    q: "Before undertaking her daring plan, what did Judith do?",
    choices: ["She prayed and fasted before God", "She consulted the high priest", "She gathered an army", "She fled to the mountains"],
    ref: "Judith 9" },

  /* ---------------- Esther ---------------- */
  { src: "Esther", type: "conceptual",
    q: "Who plotted to destroy all the Jews in the Persian empire, and was hanged on his own gallows?",
    choices: ["Haman", "Mordecai", "Ahasuerus", "Bigthan"],
    ref: "Esther 3; 7:9–10" },
  { src: "Esther", type: "conceptual",
    q: "Which Jewish feast celebrates the deliverance recounted in the Book of Esther?",
    choices: ["Purim", "Passover", "Hanukkah", "Tabernacles"],
    ref: "Esther 9:26–28" },

  /* ---------------- 1 Maccabees ---------------- */
  { src: "1 Maccabees", type: "conceptual",
    q: "Which son of Mattathias, called “the Hammer,” led the revolt against the Greek kings?",
    choices: ["Judas Maccabeus", "Jonathan", "Simon", "Eleazar"],
    ref: "1 Maccabees 3:1–9" },
  { src: "1 Maccabees", type: "conceptual",
    q: "The rededication of the Temple by the Maccabees is remembered in which feast?",
    choices: ["Hanukkah (the Dedication)", "Purim", "Pentecost", "The Day of Atonement"],
    ref: "1 Maccabees 4:36–59" },

  /* ---------------- 2 Maccabees ---------------- */
  { src: "2 Maccabees", type: "conceptual",
    q: "In 2 Maccabees 7, how many brothers were martyred with their mother for refusing to break God's law?",
    choices: ["Seven", "Three", "Ten", "Twelve"],
    ref: "2 Maccabees 7" },
  { src: "2 Maccabees", type: "conceptual",
    q: "Judas Maccabeus took up a collection for a sin offering on behalf of the dead. This passage supports which Catholic practice?",
    choices: ["Prayer for the dead", "Fasting during Lent", "The papacy", "Infant baptism"],
    ref: "2 Maccabees 12:43–46" },

  /* ---------------- Job ---------------- */
  { src: "Job", type: "fill",
    q: "“The LORD gave, and the LORD has taken away; blessed be the ____ of the LORD.”",
    choices: ["name", "will", "hand", "justice"],
    ref: "Job 1:21" },
  { src: "Job", type: "conceptual",
    q: "From what land did Job come?",
    choices: ["Uz", "Ur", "Edom", "Midian"],
    ref: "Job 1:1" },
  { src: "Job", type: "conceptual",
    q: "How did God finally answer Job?",
    choices: ["He spoke out of the whirlwind", "He sent an angel", "He appeared in a dream", "He spoke through Job's friends"],
    ref: "Job 38:1" },

  /* ---------------- Psalms ---------------- */
  { src: "Psalms", type: "fill",
    q: "“The LORD is my ____; I shall not want.”",
    choices: ["shepherd", "rock", "refuge", "light"],
    ref: "Psalm 23:1" },
  { src: "Psalms", type: "conceptual",
    q: "How many psalms are in the Book of Psalms?",
    choices: ["150", "100", "120", "176"],
    ref: "The Psalter" },
  { src: "Psalms", type: "fill",
    q: "The Miserere, David's psalm of repentance: “Create in me a clean ____, O God.”",
    choices: ["heart", "spirit", "soul", "mind"],
    ref: "Psalm 51:10" },
  { src: "Psalms", type: "conceptual",
    q: "To whom does tradition attribute many of the psalms?",
    choices: ["King David", "Moses", "Solomon", "Ezra"],
    ref: "cf. 2 Samuel 23:1" },

  /* ---------------- Proverbs ---------------- */
  { src: "Proverbs", type: "fill",
    q: "“The fear of the LORD is the beginning of ____.”",
    choices: ["wisdom", "justice", "prosperity", "peace"],
    ref: "Proverbs 9:10" },
  { src: "Proverbs", type: "fill",
    q: "“Trust in the LORD with all your ____, and do not rely on your own insight.”",
    choices: ["heart", "strength", "mind", "soul"],
    ref: "Proverbs 3:5" },
  { src: "Proverbs", type: "conceptual",
    q: "To which king is the Book of Proverbs traditionally attributed?",
    choices: ["Solomon", "David", "Hezekiah", "Josiah"],
    ref: "Proverbs 1:1" },

  /* ---------------- Ecclesiastes ---------------- */
  { src: "Ecclesiastes", type: "fill",
    q: "“Vanity of vanities! All is ____.”",
    choices: ["vanity", "fleeting", "dust", "sorrow"],
    ref: "Ecclesiastes 1:2" },
  { src: "Ecclesiastes", type: "conceptual",
    q: "By what Hebrew title does the author of Ecclesiastes call himself?",
    choices: ["Qoheleth (the Preacher)", "The Scribe", "The Servant", "The Wise One"],
    ref: "Ecclesiastes 1:1" },
  { src: "Ecclesiastes", type: "fill",
    q: "“For everything there is a season, and a time for every ____ under heaven.”",
    choices: ["matter", "creature", "labor", "hope"],
    ref: "Ecclesiastes 3:1" },

  /* ---------------- Wisdom ---------------- */
  { src: "Wisdom", type: "fill",
    q: "“The souls of the righteous are in the hand of ____, and no torment will ever touch them.”",
    choices: ["God", "the angels", "the Almighty", "their Maker"],
    ref: "Wisdom 3:1" },
  { src: "Wisdom", type: "conceptual",
    q: "According to the Book of Wisdom, how did death enter the world?",
    choices: ["Through the devil's envy", "Through Adam's pride alone", "By God's design", "Through the flood"],
    ref: "Wisdom 2:24" },

  /* ---------------- Sirach ---------------- */
  { src: "Sirach", type: "conceptual",
    q: "By what other name is the Book of Sirach known?",
    choices: ["Ecclesiasticus", "Ecclesiastes", "The Didache", "Proverbs of Ben Adam"],
    ref: "Sirach (prologue); Latin tradition" },
  { src: "Sirach", type: "conceptual",
    q: "According to Sirach, honoring one's father and mother does what?",
    choices: ["Atones for sins", "Guarantees riches", "Wins victory in battle", "Brings rain in due season"],
    ref: "Sirach 3:3–14" },

  /* ---------------- Isaiah ---------------- */
  { src: "Isaiah", type: "fill",
    q: "“Behold, a ____ shall conceive and bear a son, and shall call his name Emmanuel.”",
    choices: ["virgin", "queen", "daughter of Zion", "handmaid"],
    ref: "Isaiah 7:14" },
  { src: "Isaiah", type: "conceptual",
    q: "Which chapter of Isaiah describes the Suffering Servant, “wounded for our transgressions”?",
    choices: ["Isaiah 53", "Isaiah 6", "Isaiah 40", "Isaiah 11"],
    ref: "Isaiah 53:5" },
  { src: "Isaiah", type: "fill",
    q: "In Isaiah's temple vision the seraphim cry: “____, holy, holy is the LORD of hosts.”",
    choices: ["Holy", "Blessed", "Worthy", "Glory"],
    ref: "Isaiah 6:3" },
  { src: "Isaiah", type: "fill",
    q: "“They shall beat their swords into ____, and their spears into pruning hooks.”",
    choices: ["plowshares", "sickles", "anvils", "chains"],
    ref: "Isaiah 2:4" },

  /* ---------------- Jeremiah ---------------- */
  { src: "Jeremiah", type: "fill",
    q: "“Before I formed you in the ____ I knew you, and before you were born I consecrated you.”",
    choices: ["womb", "earth", "beginning", "garden"],
    ref: "Jeremiah 1:5" },
  { src: "Jeremiah", type: "conceptual",
    q: "What did Jeremiah prophesy that God would one day make with the house of Israel, writing His law upon their hearts?",
    choices: ["A new covenant", "A new temple", "A new kingdom", "A new priesthood"],
    ref: "Jeremiah 31:31–33" },
  { src: "Jeremiah", type: "conceptual",
    q: "Because of his sorrowful laments over Jerusalem, Jeremiah is often called what?",
    choices: ["The weeping prophet", "The prophet of fire", "The silent prophet", "The shepherd prophet"],
    ref: "cf. Jeremiah 9:1; Lamentations" },

  /* ---------------- Ezekiel ---------------- */
  { src: "Ezekiel", type: "conceptual",
    q: "In Ezekiel's famous vision, what did God command him to prophesy over so that they came to life?",
    choices: ["A valley of dry bones", "A field of wheat", "A ruined temple", "A dead sea"],
    ref: "Ezekiel 37:1–10" },
  { src: "Ezekiel", type: "fill",
    q: "“A new heart I will give you… I will take out of your flesh the heart of ____ and give you a heart of flesh.”",
    choices: ["stone", "iron", "clay", "bronze"],
    ref: "Ezekiel 36:26" },

  /* ---------------- Daniel ---------------- */
  { src: "Daniel", type: "conceptual",
    q: "Into what was Daniel thrown for praying to his God against the king's decree?",
    choices: ["A den of lions", "A fiery furnace", "A dry cistern", "A prison tower"],
    ref: "Daniel 6:16" },
  { src: "Daniel", type: "conceptual",
    q: "What were the names of the three young men who survived the fiery furnace?",
    choices: ["Shadrach, Meshach, and Abednego", "Hananiah, Nathan, and Azariel", "Belteshazzar, Arioch, and Mishael", "Eleazar, Simon, and Jonathan"],
    ref: "Daniel 3" },
  { src: "Daniel", type: "conceptual",
    q: "At Belshazzar's feast, what appeared on the palace wall?",
    choices: ["Writing by a mysterious hand", "A flaming sword", "The face of an angel", "A shadow of a lion"],
    ref: "Daniel 5:5" },

  /* ---------------- Jonah ---------------- */
  { src: "Jonah", type: "conceptual",
    q: "To which great city was Jonah sent to preach repentance?",
    choices: ["Nineveh", "Babylon", "Tarshish", "Tyre"],
    ref: "Jonah 1:2" },
  { src: "Jonah", type: "conceptual",
    q: "How long was Jonah in the belly of the great fish?",
    choices: ["Three days and three nights", "Seven days", "One day and one night", "Forty days"],
    ref: "Jonah 1:17" },

  /* ---------------- Matthew ---------------- */
  { src: "Matthew", type: "fill",
    q: "“Blessed are the poor in spirit, for theirs is the kingdom of ____.”",
    choices: ["heaven", "God", "peace", "the meek"],
    ref: "Matthew 5:3" },
  { src: "Matthew", type: "conceptual",
    q: "What gifts did the Magi bring to the child Jesus?",
    choices: ["Gold, frankincense, and myrrh", "Gold, silver, and incense", "Bread, wine, and oil", "Silk, spices, and gold"],
    ref: "Matthew 2:11" },
  { src: "Matthew", type: "fill",
    q: "“You are Peter, and on this rock I will build my ____.”",
    choices: ["church", "kingdom", "temple", "house"],
    ref: "Matthew 16:18" },
  { src: "Matthew", type: "fill",
    q: "The Great Commission: “Go therefore and make disciples of all ____.”",
    choices: ["nations", "peoples", "cities", "believers"],
    ref: "Matthew 28:19" },
  { src: "Matthew", type: "conceptual",
    q: "With what collection of blessings does the Sermon on the Mount begin?",
    choices: ["The Beatitudes", "The Our Father", "The parables of the kingdom", "The woes to the Pharisees"],
    ref: "Matthew 5:3–12" },

  /* ---------------- Mark ---------------- */
  { src: "Mark", type: "fill",
    q: "Jesus' first proclamation in Mark: “The kingdom of God is at hand; ____ and believe in the gospel.”",
    choices: ["repent", "rejoice", "watch", "rise"],
    ref: "Mark 1:15" },
  { src: "Mark", type: "conceptual",
    q: "Which apostle is Mark's Gospel traditionally said to be based on?",
    choices: ["Peter", "Paul", "John", "Andrew"],
    ref: "cf. 1 Peter 5:13; early tradition (Papias)" },
  { src: "Mark", type: "conceptual",
    q: "Who was Bartimaeus, whom Jesus healed near Jericho?",
    choices: ["A blind beggar", "A leper", "A paralytic", "A tax collector"],
    ref: "Mark 10:46–52" },

  /* ---------------- Luke ---------------- */
  { src: "Luke", type: "conceptual",
    q: "Which angel announced to Mary that she would bear the Son of God?",
    choices: ["Gabriel", "Michael", "Raphael", "An unnamed angel"],
    ref: "Luke 1:26–38" },
  { src: "Luke", type: "fill",
    q: "Mary's Magnificat begins: “My soul magnifies the ____.”",
    choices: ["Lord", "Almighty", "Most High", "Holy One"],
    ref: "Luke 1:46" },
  { src: "Luke", type: "conceptual",
    q: "Which two beloved parables are found only in Luke's Gospel?",
    choices: ["The Prodigal Son and the Good Samaritan", "The Sower and the Mustard Seed", "The Lost Sheep and the Talents", "The Wedding Feast and the Vineyard"],
    ref: "Luke 15:11–32; 10:25–37" },
  { src: "Luke", type: "fill",
    q: "From the cross Jesus prayed: “Father, ____ them; for they know not what they do.”",
    choices: ["forgive", "spare", "receive", "remember"],
    ref: "Luke 23:34" },
  { src: "Luke", type: "conceptual",
    q: "What was Luke's profession, according to St. Paul?",
    choices: ["Physician", "Fisherman", "Tentmaker", "Scribe"],
    ref: "Colossians 4:14" },

  /* ---------------- John ---------------- */
  { src: "John", type: "fill",
    q: "“In the beginning was the ____, and the Word was with God, and the Word was God.”",
    choices: ["Word", "Light", "Spirit", "Truth"],
    ref: "John 1:1" },
  { src: "John", type: "conceptual",
    q: "Where did Jesus perform His first sign, changing water into wine?",
    choices: ["The wedding at Cana", "The temple in Jerusalem", "Peter's house in Capernaum", "The pool of Bethesda"],
    ref: "John 2:1–11" },
  { src: "John", type: "fill",
    q: "“I am the way, and the truth, and the ____; no one comes to the Father, but by me.”",
    choices: ["life", "light", "door", "vine"],
    ref: "John 14:6" },
  { src: "John", type: "conceptual",
    q: "In which chapter of John does Jesus give the Bread of Life discourse — “my flesh is food indeed”?",
    choices: ["John 6", "John 3", "John 10", "John 15"],
    ref: "John 6:22–71" },
  { src: "John", type: "fill",
    q: "“For God so loved the world that he gave his only ____.”",
    choices: ["Son", "Word", "begotten", "Lamb"],
    ref: "John 3:16" },

  /* ---------------- Acts ---------------- */
  { src: "Acts", type: "conceptual",
    q: "At Pentecost, in what form did the Holy Spirit appear resting on each of the disciples?",
    choices: ["Tongues as of fire", "A dove", "A bright cloud", "A rushing river"],
    ref: "Acts 2:3" },
  { src: "Acts", type: "conceptual",
    q: "On the road to which city was Saul converted by a vision of the risen Christ?",
    choices: ["Damascus", "Antioch", "Jerusalem", "Tarsus"],
    ref: "Acts 9:3–6" },
  { src: "Acts", type: "conceptual",
    q: "Who was the first Christian martyr, stoned while Saul looked on?",
    choices: ["Stephen", "James", "Barnabas", "Philip"],
    ref: "Acts 7:54–60" },
  { src: "Acts", type: "conceptual",
    q: "In which city were the disciples first called “Christians”?",
    choices: ["Antioch", "Jerusalem", "Rome", "Ephesus"],
    ref: "Acts 11:26" },

  /* ---------------- Romans ---------------- */
  { src: "Romans", type: "fill",
    q: "“The wages of sin is ____, but the free gift of God is eternal life in Christ Jesus our Lord.”",
    choices: ["death", "sorrow", "exile", "judgment"],
    ref: "Romans 6:23" },
  { src: "Romans", type: "fill",
    q: "“All have sinned and fall short of the ____ of God.”",
    choices: ["glory", "grace", "kingdom", "mercy"],
    ref: "Romans 3:23" },
  { src: "Romans", type: "fill",
    q: "“We know that in everything God works for ____ with those who love him.”",
    choices: ["good", "glory", "salvation", "peace"],
    ref: "Romans 8:28" },

  /* ---------------- 1 Corinthians ---------------- */
  { src: "1 Corinthians", type: "fill",
    q: "“So faith, hope, love abide, these three; but the greatest of these is ____.”",
    choices: ["love", "faith", "hope", "grace"],
    ref: "1 Corinthians 13:13" },
  { src: "1 Corinthians", type: "conceptual",
    q: "Paul teaches that the Christian's body is a temple of whom?",
    choices: ["The Holy Spirit", "The Father", "The angels", "The Church"],
    ref: "1 Corinthians 6:19" },
  { src: "1 Corinthians", type: "conceptual",
    q: "In 1 Corinthians 11, Paul hands on the words of Jesus at the Last Supper: “Do this in remembrance of me.” Of which sacrament is this the institution?",
    choices: ["The Eucharist", "Baptism", "Confirmation", "Holy Orders"],
    ref: "1 Corinthians 11:23–25" },

  /* ---------------- Ephesians ---------------- */
  { src: "Ephesians", type: "fill",
    q: "“For by ____ you have been saved through faith; and this is not your own doing, it is the gift of God.”",
    choices: ["grace", "works", "hope", "mercy"],
    ref: "Ephesians 2:8" },
  { src: "Ephesians", type: "conceptual",
    q: "In Ephesians 6, Paul tells Christians to put on what, in order to stand against the devil?",
    choices: ["The whole armor of God", "The garment of praise", "The yoke of Christ", "The mantle of the prophets"],
    ref: "Ephesians 6:11–17" },

  /* ---------------- Hebrews ---------------- */
  { src: "Hebrews", type: "conceptual",
    q: "According to Hebrews, Jesus is a high priest forever after the order of whom?",
    choices: ["Melchizedek", "Aaron", "Levi", "Zadok"],
    ref: "Hebrews 7:17" },
  { src: "Hebrews", type: "fill",
    q: "“Faith is the assurance of things ____ for, the conviction of things not seen.”",
    choices: ["hoped", "prayed", "longed", "asked"],
    ref: "Hebrews 11:1" },

  /* ---------------- James ---------------- */
  { src: "James", type: "fill",
    q: "“For as the body apart from the spirit is dead, so faith apart from ____ is dead.”",
    choices: ["works", "love", "prayer", "hope"],
    ref: "James 2:26" },
  { src: "James", type: "conceptual",
    q: "James 5:14 — “Is any among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil” — is a scriptural root of which sacrament?",
    choices: ["Anointing of the Sick", "Confirmation", "Penance", "Holy Orders"],
    ref: "James 5:14–15; CCC 1510" },

  /* ---------------- Revelation ---------------- */
  { src: "Revelation", type: "conceptual",
    q: "On which island was John when he received the visions of Revelation?",
    choices: ["Patmos", "Cyprus", "Crete", "Malta"],
    ref: "Revelation 1:9" },
  { src: "Revelation", type: "fill",
    q: "“I am the Alpha and the ____, the first and the last, the beginning and the end.”",
    choices: ["Omega", "Amen", "Almighty", "Morning Star"],
    ref: "Revelation 22:13" },
  { src: "Revelation", type: "conceptual",
    q: "In Revelation 12, who appears “clothed with the sun, with the moon under her feet, and on her head a crown of twelve stars”?",
    choices: ["A woman (seen by the Church as Mary and Israel/the Church)", "The bride of the Lamb", "The angel of the church of Ephesus", "Wisdom personified"],
    ref: "Revelation 12:1" },

  /* ============================================================
     CATECHISM OF THE CATHOLIC CHURCH
     ============================================================ */

  /* ------- Part I: The Profession of Faith ------- */
  { src: "CCC Part I: The Profession of Faith", type: "fill",
    q: "“The desire for God is written in the human ____, because man is created by God and for God.”",
    choices: ["heart", "soul", "mind", "conscience"],
    ref: "CCC 27" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "What is the central mystery of the Christian faith and life?",
    choices: ["The mystery of the Most Holy Trinity", "The Incarnation", "The Resurrection", "The Immaculate Conception"],
    ref: "CCC 234" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "What are the four marks of the Church professed in the Creed?",
    choices: ["One, holy, catholic, and apostolic", "Holy, Roman, catholic, and universal", "One, faithful, apostolic, and eternal", "Visible, holy, universal, and missionary"],
    ref: "CCC 811" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "What does the word “catholic” mean?",
    choices: ["Universal", "Holy", "Roman", "Chosen"],
    ref: "CCC 830" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "What does the dogma of the Immaculate Conception teach?",
    choices: ["Mary was preserved from original sin from the first moment of her conception", "Jesus was conceived by the Holy Spirit", "Mary remained a virgin her whole life", "Mary was assumed body and soul into heaven"],
    ref: "CCC 491" },
  { src: "CCC Part I: The Profession of Faith", type: "fill",
    q: "“Man is created in the ____ and likeness of God.”",
    choices: ["image", "spirit", "wisdom", "glory"],
    ref: "CCC 355; Genesis 1:27" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "What is Purgatory?",
    choices: ["The final purification of the elect, so as to achieve the holiness necessary to enter heaven", "A second chance for the damned", "The waiting place of the just before Christ's coming", "A state of eternal separation from God"],
    ref: "CCC 1030–1031" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "The “communion of saints” includes the faithful in which three states?",
    choices: ["Pilgrims on earth, the dead being purified, and the blessed in heaven", "Priests, religious, and laity", "Martyrs, confessors, and virgins", "The baptized, the catechumens, and the angels"],
    ref: "CCC 954" },
  { src: "CCC Part I: The Profession of Faith", type: "conceptual",
    q: "From infancy to death, human life is surrounded by the watchful care and intercession of whom?",
    choices: ["The angels (each person has a guardian angel)", "The patriarchs", "The souls in purgatory", "The apostles"],
    ref: "CCC 336" },
  { src: "CCC Part I: The Profession of Faith", type: "fill",
    q: "“Faith is man's ____ to God, who reveals himself and gives himself to man.”",
    choices: ["response", "debt", "journey", "surrender"],
    ref: "CCC 26" },

  /* ------- Part II: The Sacraments ------- */
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "How many sacraments did Christ institute and entrust to the Church?",
    choices: ["Seven", "Three", "Ten", "Twelve"],
    ref: "CCC 1113" },
  { src: "CCC Part II: The Sacraments", type: "fill",
    q: "“The Eucharist is the source and ____ of the Christian life.”",
    choices: ["summit", "center", "sign", "seal"],
    ref: "CCC 1324" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "Which three sacraments are the sacraments of Christian initiation?",
    choices: ["Baptism, Confirmation, and the Eucharist", "Baptism, Penance, and the Eucharist", "Baptism, Confirmation, and Matrimony", "Baptism, the Eucharist, and Holy Orders"],
    ref: "CCC 1212" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "By what term does the Church describe the change of the bread and wine into the Body and Blood of Christ?",
    choices: ["Transubstantiation", "Consubstantiation", "Transfiguration", "Sanctification"],
    ref: "CCC 1376" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "What does Baptism forgive?",
    choices: ["Original sin and all personal sins", "Original sin only", "Venial sins only", "Sins committed after the age of reason"],
    ref: "CCC 1263" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "Which two sacraments are called the sacraments of healing?",
    choices: ["Penance and the Anointing of the Sick", "Baptism and Penance", "The Eucharist and the Anointing of the Sick", "Penance and the Eucharist"],
    ref: "CCC 1421" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "Which two sacraments are directed toward the salvation of others and are called sacraments at the service of communion?",
    choices: ["Holy Orders and Matrimony", "Confirmation and Matrimony", "Holy Orders and the Eucharist", "Baptism and Confirmation"],
    ref: "CCC 1534" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "With what is a Christian anointed in Confirmation?",
    choices: ["Sacred chrism", "The oil of catechumens", "The oil of the sick", "Blessed water"],
    ref: "CCC 1289, 1300" },
  { src: "CCC Part II: The Sacraments", type: "conceptual",
    q: "In the Latin rite, who is the ordinary minister of Confirmation?",
    choices: ["The bishop", "The pastor", "Any priest", "The deacon"],
    ref: "CCC 1313" },
  { src: "CCC Part II: The Sacraments", type: "fill",
    q: "Easter is not simply one feast among others, but the “Feast of feasts,” the “Solemnity of solemnities,” as the Eucharist is the “Sacrament of ____.”",
    choices: ["sacraments", "salvation", "the Church", "unity"],
    ref: "CCC 1169" },

  /* ------- Part III: Life in Christ ------- */
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "What three conditions must be met together for a sin to be mortal?",
    choices: ["Grave matter, full knowledge, and deliberate consent", "Grave matter, public scandal, and repetition", "Full knowledge, malice, and obstinacy", "Deliberate consent, grave harm, and lack of repentance"],
    ref: "CCC 1857" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "What are the three theological virtues?",
    choices: ["Faith, hope, and charity", "Prudence, justice, and temperance", "Faith, humility, and obedience", "Hope, mercy, and charity"],
    ref: "CCC 1813" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "What are the four cardinal virtues?",
    choices: ["Prudence, justice, fortitude, and temperance", "Faith, hope, charity, and prudence", "Wisdom, courage, patience, and justice", "Humility, chastity, diligence, and charity"],
    ref: "CCC 1805" },
  { src: "CCC Part III: Life in Christ", type: "fill",
    q: "“Conscience is man's most secret core and his ____. There he is alone with God, whose voice echoes in his depths.”",
    choices: ["sanctuary", "refuge", "judge", "compass"],
    ref: "CCC 1776" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "How many capital sins does the Church's tradition name?",
    choices: ["Seven", "Ten", "Three", "Twelve"],
    ref: "CCC 1866" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "Which commandment requires us to honor our father and our mother?",
    choices: ["The fourth", "The first", "The sixth", "The eighth"],
    ref: "CCC 2197" },
  { src: "CCC Part III: Life in Christ", type: "fill",
    q: "“Grace is favor, the free and ____ help that God gives us to respond to his call.”",
    choices: ["undeserved", "abundant", "hidden", "sanctifying"],
    ref: "CCC 1996" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "The first precept of the Church requires the faithful to do what?",
    choices: ["Attend Mass on Sundays and holy days of obligation", "Fast every Friday of the year", "Confess their sins once a month", "Tithe ten percent of their income"],
    ref: "CCC 2042" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "How many Beatitudes does Jesus proclaim in the Sermon on the Mount?",
    choices: ["Eight", "Seven", "Ten", "Twelve"],
    ref: "CCC 1716; Matthew 5:3–10" },
  { src: "CCC Part III: Life in Christ", type: "conceptual",
    q: "According to the Catechism, the human person, made in the image of God, is a being at once corporeal and what?",
    choices: ["Spiritual", "Immortal", "Rational", "Social"],
    ref: "CCC 362" },

  /* ------- Part IV: Christian Prayer ------- */
  { src: "CCC Part IV: Christian Prayer", type: "fill",
    q: "St. John Damascene: “Prayer is the raising of one's mind and heart to ____ or the requesting of good things from God.”",
    choices: ["God", "heaven", "the Father", "Christ"],
    ref: "CCC 2559" },
  { src: "CCC Part IV: Christian Prayer", type: "fill",
    q: "St. Thérèse of Lisieux: “For me, prayer is a surge of the ____; it is a simple look turned toward heaven.”",
    choices: ["heart", "soul", "spirit", "will"],
    ref: "CCC 2558" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "How many petitions does the Our Father contain?",
    choices: ["Seven", "Five", "Ten", "Three"],
    ref: "CCC 2803" },
  { src: "CCC Part IV: Christian Prayer", type: "fill",
    q: "Tertullian: “The Lord's Prayer is truly the summary of the whole ____.”",
    choices: ["gospel", "law", "faith", "Scripture"],
    ref: "CCC 2761" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "What are the three major expressions of the life of prayer?",
    choices: ["Vocal prayer, meditation, and contemplative prayer", "Petition, praise, and thanksgiving", "Liturgy, devotion, and silence", "Adoration, intercession, and blessing"],
    ref: "CCC 2699" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "Jesus taught His disciples the Our Father when they asked Him what?",
    choices: ["“Lord, teach us to pray”", "“Lord, increase our faith”", "“Lord, show us the Father”", "“Lord, to whom shall we go?”"],
    ref: "CCC 2759; Luke 11:1" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "Which forms of prayer does the Catechism name, alongside petition and intercession?",
    choices: ["Blessing and adoration, thanksgiving, and praise", "Fasting, vigils, and almsgiving", "Lament, confession, and vows", "Silence, song, and pilgrimage"],
    ref: "CCC 2626–2643" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "What are the two habitual difficulties in the “battle of prayer” named by the Catechism?",
    choices: ["Distraction and dryness", "Doubt and despair", "Fatigue and fear", "Pride and impatience"],
    ref: "CCC 2729–2731" },
  { src: "CCC Part IV: Christian Prayer", type: "conceptual",
    q: "The word “Abba,” with which Jesus addressed God, means what?",
    choices: ["Father", "Lord", "Master", "Holy One"],
    ref: "CCC 2766; Mark 14:36" },
];
