/* ============================================================
   Lectio-Intelligo — Question Bank
   ------------------------------------------------------------
   Covers all 73 books of the Catholic canon (46 OT + 27 NT)
   and all four parts of the Catechism of the Catholic Church,
   divided into the CCC's own eight sections (two per part).

   Each question:
     src     : source id (a Bible book or Catechism section)
     type    : "conceptual" | "fill"  (fill-in-the-blank)
     q       : question text ("____" marks the blank for fill)
     choices : array of 4 options; the FIRST one is correct
               (the app shuffles them at runtime)
     ref     : citation shown with the feedback
   ============================================================ */

const SOURCE_GROUPS = [
  {
    name: "The Pentateuch",
    kind: "bible",
    items: ["Genesis", "Exodus", "Leviticus", "Numbers", "Deuteronomy"],
  },
  {
    name: "Historical Books",
    kind: "bible",
    items: ["Joshua", "Judges", "Ruth", "1 Samuel", "2 Samuel", "1 Kings",
            "2 Kings", "1 Chronicles", "2 Chronicles", "Ezra", "Nehemiah",
            "Tobit", "Judith", "Esther", "1 Maccabees", "2 Maccabees"],
  },
  {
    name: "Wisdom Books",
    kind: "bible",
    items: ["Job", "Psalms", "Proverbs", "Ecclesiastes", "Song of Songs",
            "Wisdom", "Sirach"],
  },
  {
    name: "The Prophets",
    kind: "bible",
    items: ["Isaiah", "Jeremiah", "Lamentations", "Baruch", "Ezekiel",
            "Daniel", "Hosea", "Joel", "Amos", "Obadiah", "Jonah", "Micah",
            "Nahum", "Habakkuk", "Zephaniah", "Haggai", "Zechariah", "Malachi"],
  },
  {
    name: "The Gospels & Acts",
    kind: "bible",
    items: ["Matthew", "Mark", "Luke", "John", "Acts"],
  },
  {
    name: "Letters of St. Paul",
    kind: "bible",
    items: ["Romans", "1 Corinthians", "2 Corinthians", "Galatians",
            "Ephesians", "Philippians", "Colossians", "1 Thessalonians",
            "2 Thessalonians", "1 Timothy", "2 Timothy", "Titus",
            "Philemon", "Hebrews"],
  },
  {
    name: "Catholic Letters & Revelation",
    kind: "bible",
    items: ["James", "1 Peter", "2 Peter", "1 John", "2 John", "3 John",
            "Jude", "Revelation"],
  },
  {
    name: "Saints Through the Ages",
    kind: "saints",
    items: [
      "Saints — The Apostolic Age (1st century)",
      "Saints — The Early Church (2nd–5th centuries)",
      "Saints — The Middle Ages (6th–15th centuries)",
      "Saints — The Age of Reform (16th–17th centuries)",
      "Saints — The Modern Era (18th–21st centuries)",
    ],
  },
  {
    name: "Catechism of the Catholic Church",
    kind: "ccc",
    items: [
      "CCC Part I — Revelation, Scripture & Faith",
      "CCC Part I — The Creed",
      "CCC Part II — The Sacred Liturgy",
      "CCC Part II — The Seven Sacraments",
      "CCC Part III — Life in the Spirit",
      "CCC Part III — The Ten Commandments",
      "CCC Part IV — Prayer in the Christian Life",
      "CCC Part IV — The Lord's Prayer",
    ],
  },
];

const QUESTION_BANK = [

  /* ---------------- Genesis ---------------- */
  { src: "Genesis", type: "fill",
    q: "“In the beginning God created the heavens and the ____.”",
    choices: ["earth", "seas", "angels", "light"],
    ref: "Genesis 1:1" },
  { src: "Genesis", type: "conceptual",
    q: "On which day of creation did God create man?",
    choices: ["The sixth day", "The first day", "The third day", "The seventh day"],
    ref: "Genesis 1:26–31" },
  { src: "Genesis", type: "conceptual",
    q: "What sign did God give Noah as a pledge of His covenant never again to destroy the earth by flood?",
    choices: ["A rainbow", "A dove", "An olive branch", "A pillar of fire"],
    ref: "Genesis 9:12–13" },
  { src: "Genesis", type: "conceptual",
    q: "Which son of Jacob was sold into slavery in Egypt by his brothers?",
    choices: ["Joseph", "Benjamin", "Reuben", "Judah"],
    ref: "Genesis 37:28" },
  { src: "Genesis", type: "fill",
    q: "The serpent tempted Eve, saying: “You will be like God, knowing good and ____.”",
    choices: ["evil", "wisdom", "truth", "life"],
    ref: "Genesis 3:5" },

  /* ---------------- Exodus ---------------- */
  { src: "Exodus", type: "conceptual",
    q: "From what did God first speak to Moses in the wilderness?",
    choices: ["A burning bush", "A whirlwind", "A pillar of cloud", "A still small voice"],
    ref: "Exodus 3:2–4" },
  { src: "Exodus", type: "fill",
    q: "When Moses asked God His name, God replied: “I AM WHO ____.”",
    choices: ["I AM", "I WILL BE", "IS HOLY", "SENT YOU"],
    ref: "Exodus 3:14" },
  { src: "Exodus", type: "conceptual",
    q: "How many plagues did God send upon Egypt?",
    choices: ["Ten", "Seven", "Twelve", "Forty"],
    ref: "Exodus 7–12" },
  { src: "Exodus", type: "conceptual",
    q: "Which feast commemorates Israel's deliverance, when the destroyer passed over houses marked with the blood of a lamb?",
    choices: ["Passover", "Pentecost", "Tabernacles", "Purim"],
    ref: "Exodus 12:21–27" },
  { src: "Exodus", type: "conceptual",
    q: "On which mountain did Moses receive the Ten Commandments?",
    choices: ["Mount Sinai", "Mount Nebo", "Mount Carmel", "Mount Moriah"],
    ref: "Exodus 19–20" },

  /* ---------------- Leviticus ---------------- */
  { src: "Leviticus", type: "fill",
    q: "“You shall be holy; for I the LORD your God am ____.”",
    choices: ["holy", "mighty", "one", "jealous"],
    ref: "Leviticus 19:2" },
  { src: "Leviticus", type: "conceptual",
    q: "From which tribe of Israel did the priests come?",
    choices: ["Levi", "Judah", "Benjamin", "Ephraim"],
    ref: "Leviticus 8; Numbers 3" },
  { src: "Leviticus", type: "fill",
    q: "“You shall love your neighbor as ____.” — a command Jesus later calls the second greatest.",
    choices: ["yourself", "your brother", "the LORD", "your own soul"],
    ref: "Leviticus 19:18" },

  /* ---------------- Numbers ---------------- */
  { src: "Numbers", type: "conceptual",
    q: "What did Moses lift up on a pole so that those bitten by serpents might look at it and live?",
    choices: ["A bronze serpent", "The ark of the covenant", "A golden calf", "Aaron's staff"],
    ref: "Numbers 21:8–9" },
  { src: "Numbers", type: "conceptual",
    q: "For how many years did Israel wander in the wilderness?",
    choices: ["Forty", "Seven", "Twelve", "Seventy"],
    ref: "Numbers 14:33–34" },
  { src: "Numbers", type: "fill",
    q: "The priestly blessing: “The LORD bless you and ____ you.”",
    choices: ["keep", "guide", "heal", "strengthen"],
    ref: "Numbers 6:24" },

  /* ---------------- Deuteronomy ---------------- */
  { src: "Deuteronomy", type: "fill",
    q: "The Shema: “Hear, O Israel: The LORD our God, the LORD is ____.”",
    choices: ["one", "holy", "king", "near"],
    ref: "Deuteronomy 6:4" },
  { src: "Deuteronomy", type: "conceptual",
    q: "What does the name “Deuteronomy” mean?",
    choices: ["Second law", "Book of numbers", "Words of Moses", "The covenant"],
    ref: "Deuteronomy 17:18 (Greek deuteronomion)" },
  { src: "Deuteronomy", type: "fill",
    q: "“Man does not live by ____ alone, but by every word that proceeds out of the mouth of the LORD.”",
    choices: ["bread", "water", "wine", "manna"],
    ref: "Deuteronomy 8:3" },
  { src: "Deuteronomy", type: "conceptual",
    q: "From which mountain did Moses view the Promised Land before he died?",
    choices: ["Mount Nebo", "Mount Sinai", "Mount Horeb", "Mount Tabor"],
    ref: "Deuteronomy 34:1–5" },

  /* ---------------- Joshua ---------------- */
  { src: "Joshua", type: "conceptual",
    q: "The walls of which city fell after Israel marched around it for seven days?",
    choices: ["Jericho", "Ai", "Hebron", "Gibeon"],
    ref: "Joshua 6" },
  { src: "Joshua", type: "fill",
    q: "“As for me and my house, we will serve the ____.”",
    choices: ["LORD", "covenant", "law", "God of Abraham"],
    ref: "Joshua 24:15" },
  { src: "Joshua", type: "conceptual",
    q: "What body of water parted so Israel could cross into the Promised Land?",
    choices: ["The Jordan River", "The Red Sea", "The Sea of Galilee", "The Euphrates"],
    ref: "Joshua 3:14–17" },

  /* ---------------- Judges ---------------- */
  { src: "Judges", type: "conceptual",
    q: "Which judge's great strength was tied to his uncut hair?",
    choices: ["Samson", "Gideon", "Jephthah", "Ehud"],
    ref: "Judges 16:17" },
  { src: "Judges", type: "conceptual",
    q: "Who was the prophetess who judged Israel and accompanied Barak into battle?",
    choices: ["Deborah", "Jael", "Miriam", "Huldah"],
    ref: "Judges 4:4–9" },
  { src: "Judges", type: "conceptual",
    q: "With how many men did Gideon defeat the Midianites?",
    choices: ["Three hundred", "Three thousand", "Twelve hundred", "Seventy"],
    ref: "Judges 7:7" },

  /* ---------------- Ruth ---------------- */
  { src: "Ruth", type: "conceptual",
    q: "Who was Ruth's mother-in-law, whom she refused to abandon?",
    choices: ["Naomi", "Orpah", "Rachel", "Hannah"],
    ref: "Ruth 1:14–16" },
  { src: "Ruth", type: "fill",
    q: "“Where you go I will go… your people shall be my people, and your God my ____.”",
    choices: ["God", "refuge", "portion", "King"],
    ref: "Ruth 1:16" },
  { src: "Ruth", type: "conceptual",
    q: "Ruth married Boaz and became the great-grandmother of which king?",
    choices: ["David", "Saul", "Solomon", "Hezekiah"],
    ref: "Ruth 4:17" },

  /* ---------------- 1 Samuel ---------------- */
  { src: "1 Samuel", type: "fill",
    q: "Young Samuel answered the LORD's call: “Speak, for your servant ____.”",
    choices: ["hears", "waits", "believes", "obeys"],
    ref: "1 Samuel 3:10" },
  { src: "1 Samuel", type: "conceptual",
    q: "What weapon did David use to strike down Goliath?",
    choices: ["A sling and a stone", "A sword", "A spear", "A bow and arrow"],
    ref: "1 Samuel 17:49–50" },
  { src: "1 Samuel", type: "conceptual",
    q: "Who anointed both Saul and David as kings of Israel?",
    choices: ["Samuel", "Nathan", "Eli", "Elijah"],
    ref: "1 Samuel 10:1; 16:13" },

  /* ---------------- 2 Samuel ---------------- */
  { src: "2 Samuel", type: "conceptual",
    q: "Which prophet confronted David over his sin with Bathsheba, saying “You are the man”?",
    choices: ["Nathan", "Samuel", "Gad", "Elisha"],
    ref: "2 Samuel 12:7" },
  { src: "2 Samuel", type: "conceptual",
    q: "What did David bring up to Jerusalem, dancing before the LORD with all his might?",
    choices: ["The ark of the covenant", "The tablets of the law", "The temple treasures", "The bronze serpent"],
    ref: "2 Samuel 6:14–15" },
  { src: "2 Samuel", type: "conceptual",
    q: "Which son of David led a rebellion against him and died caught in a tree?",
    choices: ["Absalom", "Amnon", "Adonijah", "Solomon"],
    ref: "2 Samuel 15; 18:9–15" },

  /* ---------------- 1 Kings ---------------- */
  { src: "1 Kings", type: "conceptual",
    q: "When God offered Solomon anything he wished, what did Solomon ask for?",
    choices: ["Wisdom (an understanding mind)", "Long life", "Riches", "Victory over his enemies"],
    ref: "1 Kings 3:5–9" },
  { src: "1 Kings", type: "conceptual",
    q: "Which prophet challenged the prophets of Baal to a contest on Mount Carmel?",
    choices: ["Elijah", "Elisha", "Isaiah", "Micaiah"],
    ref: "1 Kings 18:20–40" },
  { src: "1 Kings", type: "conceptual",
    q: "What great work did Solomon build in Jerusalem?",
    choices: ["The Temple of the LORD", "The city walls", "The tower of David", "The pools of Siloam"],
    ref: "1 Kings 6" },

  /* ---------------- 2 Kings ---------------- */
  { src: "2 Kings", type: "conceptual",
    q: "How was the prophet Elijah taken up into heaven?",
    choices: ["In a whirlwind, with a chariot of fire", "On the wings of angels", "In his sleep", "From the top of Mount Carmel in a cloud"],
    ref: "2 Kings 2:11" },
  { src: "2 Kings", type: "conceptual",
    q: "Naaman the Syrian was cleansed of leprosy by washing seven times in which river?",
    choices: ["The Jordan", "The Nile", "The Abana", "The Euphrates"],
    ref: "2 Kings 5:10–14" },
  { src: "2 Kings", type: "conceptual",
    q: "Which empire destroyed Jerusalem and the Temple and carried Judah into exile?",
    choices: ["Babylon", "Assyria", "Persia", "Egypt"],
    ref: "2 Kings 25" },

  /* ---------------- 1 Chronicles ---------------- */
  { src: "1 Chronicles", type: "conceptual",
    q: "After its opening genealogies, 1 Chronicles centers on which king and his preparations for the temple?",
    choices: ["David", "Saul", "Solomon", "Hezekiah"],
    ref: "1 Chronicles 11–29" },
  { src: "1 Chronicles", type: "fill",
    q: "David's blessing: “Yours, O LORD, are the greatness and the power and the glory and the victory and the ____.”",
    choices: ["majesty", "dominion", "honor", "wisdom"],
    ref: "1 Chronicles 29:11" },

  /* ---------------- 2 Chronicles ---------------- */
  { src: "2 Chronicles", type: "fill",
    q: "“If my people who are called by my name humble themselves, and pray and seek my face… then I will hear from heaven, and will forgive their sin and heal their ____.”",
    choices: ["land", "hearts", "wounds", "cities"],
    ref: "2 Chronicles 7:14" },
  { src: "2 Chronicles", type: "conceptual",
    q: "With whose decree, permitting the exiles to return and rebuild the house of the LORD, does 2 Chronicles end?",
    choices: ["Cyrus, king of Persia", "Nebuchadnezzar of Babylon", "Darius the Mede", "Artaxerxes"],
    ref: "2 Chronicles 36:22–23" },

  /* ---------------- Ezra ---------------- */
  { src: "Ezra", type: "conceptual",
    q: "What was Ezra's role among the returned exiles?",
    choices: ["A priest and scribe skilled in the law of Moses", "A governor appointed by Babylon", "A military commander", "A temple musician"],
    ref: "Ezra 7:6, 11" },
  { src: "Ezra", type: "conceptual",
    q: "What did the exiles who returned under Zerubbabel rebuild in the Book of Ezra?",
    choices: ["The temple of the LORD", "The walls of Jerusalem", "The palace of David", "The cities of Judah"],
    ref: "Ezra 3–6" },

  /* ---------------- Nehemiah ---------------- */
  { src: "Nehemiah", type: "conceptual",
    q: "What did Nehemiah lead the people of Jerusalem to rebuild in fifty-two days?",
    choices: ["The walls of the city", "The temple", "The king's highway", "The altar of sacrifice"],
    ref: "Nehemiah 2–6" },
  { src: "Nehemiah", type: "fill",
    q: "“Do not be grieved, for the joy of the LORD is your ____.”",
    choices: ["strength", "reward", "shield", "song"],
    ref: "Nehemiah 8:10" },

  /* ---------------- Tobit ---------------- */
  { src: "Tobit", type: "conceptual",
    q: "Which archangel, disguised as a traveler, accompanied young Tobias on his journey?",
    choices: ["Raphael", "Michael", "Gabriel", "Uriel"],
    ref: "Tobit 5:4; 12:15" },
  { src: "Tobit", type: "conceptual",
    q: "What remedy healed Tobit's blindness?",
    choices: ["The gall of a fish", "Water from the Jordan", "Oil blessed by a priest", "The touch of an angel's hand"],
    ref: "Tobit 11:7–13" },
  { src: "Tobit", type: "conceptual",
    q: "Whom did Tobias marry, after a demon had slain her seven previous bridegrooms?",
    choices: ["Sarah", "Anna", "Edna", "Susanna"],
    ref: "Tobit 3:7–8; 7:11–13" },

  /* ---------------- Judith ---------------- */
  { src: "Judith", type: "conceptual",
    q: "Judith delivered Israel by beheading which enemy general?",
    choices: ["Holofernes", "Sennacherib", "Nicanor", "Sisera"],
    ref: "Judith 13:6–10" },
  { src: "Judith", type: "conceptual",
    q: "Before undertaking her daring plan, what did Judith do?",
    choices: ["She prayed and fasted before God", "She consulted the high priest", "She gathered an army", "She fled to the mountains"],
    ref: "Judith 9" },

  /* ---------------- Esther ---------------- */
  { src: "Esther", type: "conceptual",
    q: "Who plotted to destroy all the Jews in the Persian empire, and was hanged on his own gallows?",
    choices: ["Haman", "Mordecai", "Ahasuerus", "Bigthan"],
    ref: "Esther 3; 7:9–10" },
  { src: "Esther", type: "conceptual",
    q: "Which Jewish feast celebrates the deliverance recounted in the Book of Esther?",
    choices: ["Purim", "Passover", "Hanukkah", "Tabernacles"],
    ref: "Esther 9:26–28" },

  /* ---------------- 1 Maccabees ---------------- */
  { src: "1 Maccabees", type: "conceptual",
    q: "Which son of Mattathias, called “the Hammer,” led the revolt against the Greek kings?",
    choices: ["Judas Maccabeus", "Jonathan", "Simon", "Eleazar"],
    ref: "1 Maccabees 3:1–9" },
  { src: "1 Maccabees", type: "conceptual",
    q: "The rededication of the Temple by the Maccabees is remembered in which feast?",
    choices: ["Hanukkah (the Dedication)", "Purim", "Pentecost", "The Day of Atonement"],
    ref: "1 Maccabees 4:36–59" },

  /* ---------------- 2 Maccabees ---------------- */
  { src: "2 Maccabees", type: "conceptual",
    q: "In 2 Maccabees 7, how many brothers were martyred with their mother for refusing to break God's law?",
    choices: ["Seven", "Three", "Ten", "Twelve"],
    ref: "2 Maccabees 7" },
  { src: "2 Maccabees", type: "conceptual",
    q: "Judas Maccabeus took up a collection for a sin offering on behalf of the dead. This passage supports which Catholic practice?",
    choices: ["Prayer for the dead", "Fasting during Lent", "The papacy", "Infant baptism"],
    ref: "2 Maccabees 12:43–46" },

  /* ---------------- Job ---------------- */
  { src: "Job", type: "fill",
    q: "“The LORD gave, and the LORD has taken away; blessed be the ____ of the LORD.”",
    choices: ["name", "will", "hand", "justice"],
    ref: "Job 1:21" },
  { src: "Job", type: "conceptual",
    q: "From what land did Job come?",
    choices: ["Uz", "Ur", "Edom", "Midian"],
    ref: "Job 1:1" },
  { src: "Job", type: "conceptual",
    q: "How did God finally answer Job?",
    choices: ["He spoke out of the whirlwind", "He sent an angel", "He appeared in a dream", "He spoke through Job's friends"],
    ref: "Job 38:1" },

  /* ---------------- Psalms ---------------- */
  { src: "Psalms", type: "fill",
    q: "“The LORD is my ____; I shall not want.”",
    choices: ["shepherd", "rock", "refuge", "light"],
    ref: "Psalm 23:1" },
  { src: "Psalms", type: "conceptual",
    q: "How many psalms are in the Book of Psalms?",
    choices: ["150", "100", "120", "176"],
    ref: "The Psalter" },
  { src: "Psalms", type: "fill",
    q: "The Miserere, David's psalm of repentance: “Create in me a clean ____, O God.”",
    choices: ["heart", "spirit", "soul", "mind"],
    ref: "Psalm 51:10" },
  { src: "Psalms", type: "conceptual",
    q: "To whom does tradition attribute many of the psalms?",
    choices: ["King David", "Moses", "Solomon", "Ezra"],
    ref: "cf. 2 Samuel 23:1" },

  /* ---------------- Proverbs ---------------- */
  { src: "Proverbs", type: "fill",
    q: "“The fear of the LORD is the beginning of ____.”",
    choices: ["wisdom", "justice", "prosperity", "peace"],
    ref: "Proverbs 9:10" },
  { src: "Proverbs", type: "fill",
    q: "“Trust in the LORD with all your ____, and do not rely on your own insight.”",
    choices: ["heart", "strength", "mind", "soul"],
    ref: "Proverbs 3:5" },
  { src: "Proverbs", type: "conceptual",
    q: "To which king is the Book of Proverbs traditionally attributed?",
    choices: ["Solomon", "David", "Hezekiah", "Josiah"],
    ref: "Proverbs 1:1" },

  /* ---------------- Ecclesiastes ---------------- */
  { src: "Ecclesiastes", type: "fill",
    q: "“Vanity of vanities! All is ____.”",
    choices: ["vanity", "fleeting", "dust", "sorrow"],
    ref: "Ecclesiastes 1:2" },
  { src: "Ecclesiastes", type: "conceptual",
    q: "By what Hebrew title does the author of Ecclesiastes call himself?",
    choices: ["Qoheleth (the Preacher)", "The Scribe", "The Servant", "The Wise One"],
    ref: "Ecclesiastes 1:1" },
  { src: "Ecclesiastes", type: "fill",
    q: "“For everything there is a season, and a time for every ____ under heaven.”",
    choices: ["matter", "creature", "labor", "hope"],
    ref: "Ecclesiastes 3:1" },

  /* ---------------- Song of Songs ---------------- */
  { src: "Song of Songs", type: "fill",
    q: "“I am my beloved's and my beloved is ____.”",
    choices: ["mine", "faithful", "near", "my own"],
    ref: "Song of Songs 6:3" },
  { src: "Song of Songs", type: "fill",
    q: "“Set me as a seal upon your heart… for love is strong as ____.”",
    choices: ["death", "fire", "iron", "the sea"],
    ref: "Song of Songs 8:6" },
  { src: "Song of Songs", type: "conceptual",
    q: "How has Christian tradition long read the Song of Songs?",
    choices: ["As an image of God's love for His people and Christ's love for the Church",
              "As a manual of court etiquette",
              "As a history of Solomon's reign",
              "As a lament over the exile"],
    ref: "cf. CCC 1611" },

  /* ---------------- Wisdom ---------------- */
  { src: "Wisdom", type: "fill",
    q: "“The souls of the righteous are in the hand of ____, and no torment will ever touch them.”",
    choices: ["God", "the angels", "the Almighty", "their Maker"],
    ref: "Wisdom 3:1" },
  { src: "Wisdom", type: "conceptual",
    q: "According to the Book of Wisdom, how did death enter the world?",
    choices: ["Through the devil's envy", "Through Adam's pride alone", "By God's design", "Through the flood"],
    ref: "Wisdom 2:24" },

  /* ---------------- Sirach ---------------- */
  { src: "Sirach", type: "conceptual",
    q: "By what other name is the Book of Sirach known?",
    choices: ["Ecclesiasticus", "Ecclesiastes", "The Didache", "Proverbs of Ben Adam"],
    ref: "Sirach (prologue); Latin tradition" },
  { src: "Sirach", type: "conceptual",
    q: "According to Sirach, honoring one's father and mother does what?",
    choices: ["Atones for sins", "Guarantees riches", "Wins victory in battle", "Brings rain in due season"],
    ref: "Sirach 3:3–14" },

  /* ---------------- Isaiah ---------------- */
  { src: "Isaiah", type: "fill",
    q: "“Behold, a ____ shall conceive and bear a son, and shall call his name Emmanuel.”",
    choices: ["virgin", "queen", "daughter of Zion", "handmaid"],
    ref: "Isaiah 7:14" },
  { src: "Isaiah", type: "conceptual",
    q: "Which chapter of Isaiah describes the Suffering Servant, “wounded for our transgressions”?",
    choices: ["Isaiah 53", "Isaiah 6", "Isaiah 40", "Isaiah 11"],
    ref: "Isaiah 53:5" },
  { src: "Isaiah", type: "fill",
    q: "In Isaiah's temple vision the seraphim cry: “____, holy, holy is the LORD of hosts.”",
    choices: ["Holy", "Blessed", "Worthy", "Glory"],
    ref: "Isaiah 6:3" },
  { src: "Isaiah", type: "fill",
    q: "“They shall beat their swords into ____, and their spears into pruning hooks.”",
    choices: ["plowshares", "sickles", "anvils", "chains"],
    ref: "Isaiah 2:4" },

  /* ---------------- Jeremiah ---------------- */
  { src: "Jeremiah", type: "fill",
    q: "“Before I formed you in the ____ I knew you, and before you were born I consecrated you.”",
    choices: ["womb", "earth", "beginning", "garden"],
    ref: "Jeremiah 1:5" },
  { src: "Jeremiah", type: "conceptual",
    q: "What did Jeremiah prophesy that God would one day make with the house of Israel, writing His law upon their hearts?",
    choices: ["A new covenant", "A new temple", "A new kingdom", "A new priesthood"],
    ref: "Jeremiah 31:31–33" },
  { src: "Jeremiah", type: "conceptual",
    q: "Because of his sorrowful laments over Jerusalem, Jeremiah is often called what?",
    choices: ["The weeping prophet", "The prophet of fire", "The silent prophet", "The shepherd prophet"],
    ref: "cf. Jeremiah 9:1; Lamentations" },

  /* ---------------- Lamentations ---------------- */
  { src: "Lamentations", type: "conceptual",
    q: "The Book of Lamentations mourns which event?",
    choices: ["The destruction of Jerusalem and its temple by Babylon",
              "The death of Moses",
              "The division of the kingdom",
              "The fall of Nineveh"],
    ref: "Lamentations 1" },
  { src: "Lamentations", type: "fill",
    q: "“The steadfast love of the LORD never ceases, his mercies never come to an end; they are new every ____.”",
    choices: ["morning", "season", "sabbath", "generation"],
    ref: "Lamentations 3:22–23" },

  /* ---------------- Baruch ---------------- */
  { src: "Baruch", type: "conceptual",
    q: "Who was Baruch, the author to whom this book is attributed?",
    choices: ["The scribe and companion of the prophet Jeremiah",
              "A priest of the second temple",
              "A king of Judah",
              "A prophet of the northern kingdom"],
    ref: "Baruch 1:1; Jeremiah 36:4" },
  { src: "Baruch", type: "conceptual",
    q: "To whom is the message of the Book of Baruch addressed?",
    choices: ["The Jewish exiles in Babylon", "The kings of Persia", "The priests of Jerusalem", "The Gentile nations"],
    ref: "Baruch 1:1–14" },

  /* ---------------- Ezekiel ---------------- */
  { src: "Ezekiel", type: "conceptual",
    q: "In Ezekiel's famous vision, what did God command him to prophesy over so that they came to life?",
    choices: ["A valley of dry bones", "A field of wheat", "A ruined temple", "A dead sea"],
    ref: "Ezekiel 37:1–10" },
  { src: "Ezekiel", type: "fill",
    q: "“A new heart I will give you… I will take out of your flesh the heart of ____ and give you a heart of flesh.”",
    choices: ["stone", "iron", "clay", "bronze"],
    ref: "Ezekiel 36:26" },

  /* ---------------- Daniel ---------------- */
  { src: "Daniel", type: "conceptual",
    q: "Into what was Daniel thrown for praying to his God against the king's decree?",
    choices: ["A den of lions", "A fiery furnace", "A dry cistern", "A prison tower"],
    ref: "Daniel 6:16" },
  { src: "Daniel", type: "conceptual",
    q: "What were the names of the three young men who survived the fiery furnace?",
    choices: ["Shadrach, Meshach, and Abednego", "Hananiah, Nathan, and Azariel", "Belteshazzar, Arioch, and Mishael", "Eleazar, Simon, and Jonathan"],
    ref: "Daniel 3" },
  { src: "Daniel", type: "conceptual",
    q: "At Belshazzar's feast, what appeared on the palace wall?",
    choices: ["Writing by a mysterious hand", "A flaming sword", "The face of an angel", "A shadow of a lion"],
    ref: "Daniel 5:5" },

  /* ---------------- Hosea ---------------- */
  { src: "Hosea", type: "conceptual",
    q: "God commanded Hosea to marry Gomer, an unfaithful wife, as a living sign of what?",
    choices: ["Israel's unfaithfulness to God and God's steadfast love",
              "The coming exile in Babylon",
              "The corruption of the priesthood",
              "The division of the twelve tribes"],
    ref: "Hosea 1–3" },
  { src: "Hosea", type: "fill",
    q: "“For I desire steadfast love and not ____, the knowledge of God, rather than burnt offerings.”",
    choices: ["sacrifice", "incense", "gold", "fasting"],
    ref: "Hosea 6:6" },

  /* ---------------- Joel ---------------- */
  { src: "Joel", type: "fill",
    q: "“Rend your ____ and not your garments. Return to the LORD, your God.”",
    choices: ["hearts", "souls", "robes", "sins"],
    ref: "Joel 2:13" },
  { src: "Joel", type: "conceptual",
    q: "Which prophecy of Joel did St. Peter proclaim as fulfilled on the day of Pentecost?",
    choices: ["“I will pour out my spirit on all flesh”",
              "“The day of the LORD is great and terrible”",
              "“The mountains shall drip sweet wine”",
              "“Beat your plowshares into swords”"],
    ref: "Joel 2:28; Acts 2:16–17" },

  /* ---------------- Amos ---------------- */
  { src: "Amos", type: "conceptual",
    q: "What was Amos's occupation before God called him to prophesy?",
    choices: ["A herdsman and dresser of sycamore trees", "A priest of Bethel", "A royal scribe", "A fisherman"],
    ref: "Amos 7:14" },
  { src: "Amos", type: "fill",
    q: "“Let justice roll down like ____, and righteousness like an ever-flowing stream.”",
    choices: ["waters", "thunder", "mountains", "the dawn"],
    ref: "Amos 5:24" },

  /* ---------------- Obadiah ---------------- */
  { src: "Obadiah", type: "conceptual",
    q: "Obadiah, the shortest book of the Old Testament, prophesies judgment against which nation?",
    choices: ["Edom", "Moab", "Assyria", "Philistia"],
    ref: "Obadiah 1" },
  { src: "Obadiah", type: "conceptual",
    q: "Edom was condemned for gloating over the calamity of whom?",
    choices: ["Their brother Jacob (Judah), in the day of Jerusalem's ruin", "Egypt", "Nineveh", "The Philistines"],
    ref: "Obadiah 10–14" },

  /* ---------------- Jonah ---------------- */
  { src: "Jonah", type: "conceptual",
    q: "To which great city was Jonah sent to preach repentance?",
    choices: ["Nineveh", "Babylon", "Tarshish", "Tyre"],
    ref: "Jonah 1:2" },
  { src: "Jonah", type: "conceptual",
    q: "How long was Jonah in the belly of the great fish?",
    choices: ["Three days and three nights", "Seven days", "One day and one night", "Forty days"],
    ref: "Jonah 1:17" },

  /* ---------------- Micah ---------------- */
  { src: "Micah", type: "conceptual",
    q: "Micah foretold that the ruler of Israel, “whose origin is from of old,” would come from which town?",
    choices: ["Bethlehem", "Nazareth", "Jerusalem", "Hebron"],
    ref: "Micah 5:2" },
  { src: "Micah", type: "fill",
    q: "“What does the LORD require of you but to do justice, and to love kindness, and to walk ____ with your God?”",
    choices: ["humbly", "faithfully", "daily", "uprightly"],
    ref: "Micah 6:8" },

  /* ---------------- Nahum ---------------- */
  { src: "Nahum", type: "conceptual",
    q: "Nahum prophesies the downfall of which city, the capital of Assyria?",
    choices: ["Nineveh", "Babylon", "Damascus", "Tyre"],
    ref: "Nahum 1:1" },
  { src: "Nahum", type: "fill",
    q: "“The LORD is slow to ____ and of great might, and the LORD will by no means clear the guilty.”",
    choices: ["anger", "judge", "wrath", "punish"],
    ref: "Nahum 1:3" },

  /* ---------------- Habakkuk ---------------- */
  { src: "Habakkuk", type: "fill",
    q: "“The righteous shall live by his ____” — words St. Paul later takes up in Romans and Galatians.",
    choices: ["faith", "works", "hope", "law"],
    ref: "Habakkuk 2:4" },
  { src: "Habakkuk", type: "conceptual",
    q: "How does the Book of Habakkuk begin?",
    choices: ["With the prophet's complaint, asking God why the wicked prosper",
              "With a vision of the heavenly throne",
              "With a call to rebuild the temple",
              "With an oracle against Egypt"],
    ref: "Habakkuk 1:2–4" },

  /* ---------------- Zephaniah ---------------- */
  { src: "Zephaniah", type: "conceptual",
    q: "What is the central theme of Zephaniah's prophecy?",
    choices: ["The coming day of the LORD", "The rebuilding of the temple", "The fall of Edom", "The reign of the Messiah in Bethlehem"],
    ref: "Zephaniah 1:14–18" },
  { src: "Zephaniah", type: "fill",
    q: "“The LORD, your God, is in your ____, a warrior who gives victory; he will rejoice over you with gladness.”",
    choices: ["midst", "city", "heart", "temple"],
    ref: "Zephaniah 3:17" },

  /* ---------------- Haggai ---------------- */
  { src: "Haggai", type: "conceptual",
    q: "What did Haggai urge the returned exiles to do?",
    choices: ["Rebuild the temple of the LORD", "Fast for forty days", "Return to Babylon", "Anoint a new king"],
    ref: "Haggai 1:2–8" },
  { src: "Haggai", type: "fill",
    q: "“Is it a time for you yourselves to dwell in your paneled houses, while this house lies in ____?”",
    choices: ["ruins", "darkness", "silence", "shame"],
    ref: "Haggai 1:4" },

  /* ---------------- Zechariah ---------------- */
  { src: "Zechariah", type: "fill",
    q: "“Rejoice greatly, O daughter of Zion!… Lo, your king comes to you… humble and riding on an ____” — fulfilled on Palm Sunday.",
    choices: ["ass", "horse", "camel", "mule"],
    ref: "Zechariah 9:9; Matthew 21:5" },
  { src: "Zechariah", type: "fill",
    q: "“They shall look on him whom they have ____” — words St. John applies to the crucified Christ.",
    choices: ["pierced", "rejected", "mocked", "slain"],
    ref: "Zechariah 12:10; John 19:37" },

  /* ---------------- Malachi ---------------- */
  { src: "Malachi", type: "conceptual",
    q: "What place does Malachi hold in the Christian Old Testament?",
    choices: ["It is the last book", "It is the first of the prophets", "It is the oldest book", "It is the longest of the minor prophets"],
    ref: "Canonical order of the Old Testament" },
  { src: "Malachi", type: "conceptual",
    q: "Malachi foretold that God would send which prophet before the great day of the LORD — a promise Jesus applies to John the Baptist?",
    choices: ["Elijah", "Moses", "Enoch", "Jeremiah"],
    ref: "Malachi 4:5; Matthew 17:12–13" },
  { src: "Malachi", type: "fill",
    q: "“From the rising of the sun to its setting my name is great among the nations… and a pure ____ is offered to my name” — read by the Church of the sacrifice of the Mass.",
    choices: ["offering", "incense", "lamb", "prayer"],
    ref: "Malachi 1:11" },

  /* ---------------- Matthew ---------------- */
  { src: "Matthew", type: "fill",
    q: "“Blessed are the poor in spirit, for theirs is the kingdom of ____.”",
    choices: ["heaven", "God", "peace", "the meek"],
    ref: "Matthew 5:3" },
  { src: "Matthew", type: "conceptual",
    q: "What gifts did the Magi bring to the child Jesus?",
    choices: ["Gold, frankincense, and myrrh", "Gold, silver, and incense", "Bread, wine, and oil", "Silk, spices, and gold"],
    ref: "Matthew 2:11" },
  { src: "Matthew", type: "fill",
    q: "“You are Peter, and on this rock I will build my ____.”",
    choices: ["church", "kingdom", "temple", "house"],
    ref: "Matthew 16:18" },
  { src: "Matthew", type: "fill",
    q: "The Great Commission: “Go therefore and make disciples of all ____.”",
    choices: ["nations", "peoples", "cities", "believers"],
    ref: "Matthew 28:19" },
  { src: "Matthew", type: "conceptual",
    q: "With what collection of blessings does the Sermon on the Mount begin?",
    choices: ["The Beatitudes", "The Our Father", "The parables of the kingdom", "The woes to the Pharisees"],
    ref: "Matthew 5:3–12" },

  /* ---------------- Mark ---------------- */
  { src: "Mark", type: "fill",
    q: "Jesus' first proclamation in Mark: “The kingdom of God is at hand; ____ and believe in the gospel.”",
    choices: ["repent", "rejoice", "watch", "rise"],
    ref: "Mark 1:15" },
  { src: "Mark", type: "conceptual",
    q: "Which apostle is Mark's Gospel traditionally said to be based on?",
    choices: ["Peter", "Paul", "John", "Andrew"],
    ref: "cf. 1 Peter 5:13; early tradition (Papias)" },
  { src: "Mark", type: "conceptual",
    q: "Who was Bartimaeus, whom Jesus healed near Jericho?",
    choices: ["A blind beggar", "A leper", "A paralytic", "A tax collector"],
    ref: "Mark 10:46–52" },

  /* ---------------- Luke ---------------- */
  { src: "Luke", type: "conceptual",
    q: "Which angel announced to Mary that she would bear the Son of God?",
    choices: ["Gabriel", "Michael", "Raphael", "An unnamed angel"],
    ref: "Luke 1:26–38" },
  { src: "Luke", type: "fill",
    q: "Mary's Magnificat begins: “My soul magnifies the ____.”",
    choices: ["Lord", "Almighty", "Most High", "Holy One"],
    ref: "Luke 1:46" },
  { src: "Luke", type: "conceptual",
    q: "Which two beloved parables are found only in Luke's Gospel?",
    choices: ["The Prodigal Son and the Good Samaritan", "The Sower and the Mustard Seed", "The Lost Sheep and the Talents", "The Wedding Feast and the Vineyard"],
    ref: "Luke 15:11–32; 10:25–37" },
  { src: "Luke", type: "fill",
    q: "From the cross Jesus prayed: “Father, ____ them; for they know not what they do.”",
    choices: ["forgive", "spare", "receive", "remember"],
    ref: "Luke 23:34" },
  { src: "Luke", type: "conceptual",
    q: "What was Luke's profession, according to St. Paul?",
    choices: ["Physician", "Fisherman", "Tentmaker", "Scribe"],
    ref: "Colossians 4:14" },

  /* ---------------- John ---------------- */
  { src: "John", type: "fill",
    q: "“In the beginning was the ____, and the Word was with God, and the Word was God.”",
    choices: ["Word", "Light", "Spirit", "Truth"],
    ref: "John 1:1" },
  { src: "John", type: "conceptual",
    q: "Where did Jesus perform His first sign, changing water into wine?",
    choices: ["The wedding at Cana", "The temple in Jerusalem", "Peter's house in Capernaum", "The pool of Bethesda"],
    ref: "John 2:1–11" },
  { src: "John", type: "fill",
    q: "“I am the way, and the truth, and the ____; no one comes to the Father, but by me.”",
    choices: ["life", "light", "door", "vine"],
    ref: "John 14:6" },
  { src: "John", type: "conceptual",
    q: "In which chapter of John does Jesus give the Bread of Life discourse — “my flesh is food indeed”?",
    choices: ["John 6", "John 3", "John 10", "John 15"],
    ref: "John 6:22–71" },
  { src: "John", type: "fill",
    q: "“For God so loved the world that he gave his only ____.”",
    choices: ["Son", "Word", "begotten", "Lamb"],
    ref: "John 3:16" },

  /* ---------------- Acts ---------------- */
  { src: "Acts", type: "conceptual",
    q: "At Pentecost, in what form did the Holy Spirit appear resting on each of the disciples?",
    choices: ["Tongues as of fire", "A dove", "A bright cloud", "A rushing river"],
    ref: "Acts 2:3" },
  { src: "Acts", type: "conceptual",
    q: "On the road to which city was Saul converted by a vision of the risen Christ?",
    choices: ["Damascus", "Antioch", "Jerusalem", "Tarsus"],
    ref: "Acts 9:3–6" },
  { src: "Acts", type: "conceptual",
    q: "Who was the first Christian martyr, stoned while Saul looked on?",
    choices: ["Stephen", "James", "Barnabas", "Philip"],
    ref: "Acts 7:54–60" },
  { src: "Acts", type: "conceptual",
    q: "In which city were the disciples first called “Christians”?",
    choices: ["Antioch", "Jerusalem", "Rome", "Ephesus"],
    ref: "Acts 11:26" },

  /* ---------------- Romans ---------------- */
  { src: "Romans", type: "fill",
    q: "“The wages of sin is ____, but the free gift of God is eternal life in Christ Jesus our Lord.”",
    choices: ["death", "sorrow", "exile", "judgment"],
    ref: "Romans 6:23" },
  { src: "Romans", type: "fill",
    q: "“All have sinned and fall short of the ____ of God.”",
    choices: ["glory", "grace", "kingdom", "mercy"],
    ref: "Romans 3:23" },
  { src: "Romans", type: "fill",
    q: "“We know that in everything God works for ____ with those who love him.”",
    choices: ["good", "glory", "salvation", "peace"],
    ref: "Romans 8:28" },

  /* ---------------- 1 Corinthians ---------------- */
  { src: "1 Corinthians", type: "fill",
    q: "“So faith, hope, love abide, these three; but the greatest of these is ____.”",
    choices: ["love", "faith", "hope", "grace"],
    ref: "1 Corinthians 13:13" },
  { src: "1 Corinthians", type: "conceptual",
    q: "Paul teaches that the Christian's body is a temple of whom?",
    choices: ["The Holy Spirit", "The Father", "The angels", "The Church"],
    ref: "1 Corinthians 6:19" },
  { src: "1 Corinthians", type: "conceptual",
    q: "In 1 Corinthians 11, Paul hands on the words of Jesus at the Last Supper: “Do this in remembrance of me.” Of which sacrament is this the institution?",
    choices: ["The Eucharist", "Baptism", "Confirmation", "Holy Orders"],
    ref: "1 Corinthians 11:23–25" },

  /* ---------------- 2 Corinthians ---------------- */
  { src: "2 Corinthians", type: "fill",
    q: "“Each one must do as he has made up his mind… for God loves a cheerful ____.”",
    choices: ["giver", "heart", "servant", "worker"],
    ref: "2 Corinthians 9:7" },
  { src: "2 Corinthians", type: "fill",
    q: "The Lord said to Paul: “My grace is sufficient for you, for my power is made perfect in ____.”",
    choices: ["weakness", "suffering", "faith", "silence"],
    ref: "2 Corinthians 12:9" },
  { src: "2 Corinthians", type: "conceptual",
    q: "Paul says we hold the treasure of the gospel in what, “to show that the transcendent power belongs to God”?",
    choices: ["Earthen vessels", "Golden lampstands", "Sealed scrolls", "Wineskins"],
    ref: "2 Corinthians 4:7" },

  /* ---------------- Galatians ---------------- */
  { src: "Galatians", type: "fill",
    q: "“I have been crucified with Christ; it is no longer I who live, but ____ who lives in me.”",
    choices: ["Christ", "the Spirit", "grace", "the Lord"],
    ref: "Galatians 2:20" },
  { src: "Galatians", type: "conceptual",
    q: "Galatians 5 lists love, joy, peace, patience, kindness, goodness, faithfulness, gentleness, and self-control as what?",
    choices: ["The fruit of the Spirit", "The gifts of the Spirit", "The works of the law", "The beatitudes"],
    ref: "Galatians 5:22–23" },

  /* ---------------- Ephesians ---------------- */
  { src: "Ephesians", type: "fill",
    q: "“For by ____ you have been saved through faith; and this is not your own doing, it is the gift of God.”",
    choices: ["grace", "works", "hope", "mercy"],
    ref: "Ephesians 2:8" },
  { src: "Ephesians", type: "conceptual",
    q: "In Ephesians 6, Paul tells Christians to put on what, in order to stand against the devil?",
    choices: ["The whole armor of God", "The garment of praise", "The yoke of Christ", "The mantle of the prophets"],
    ref: "Ephesians 6:11–17" },

  /* ---------------- Philippians ---------------- */
  { src: "Philippians", type: "fill",
    q: "“At the name of Jesus every knee should ____, in heaven and on earth and under the earth.”",
    choices: ["bow", "bend", "kneel", "tremble"],
    ref: "Philippians 2:10" },
  { src: "Philippians", type: "conceptual",
    q: "The great hymn of Philippians 2 says Christ, “though he was in the form of God,” did what, “taking the form of a servant”?",
    choices: ["Emptied himself", "Hid his glory", "Veiled his power", "Set aside his throne"],
    ref: "Philippians 2:6–7" },
  { src: "Philippians", type: "fill",
    q: "“I can do all things in him who ____ me.”",
    choices: ["strengthens", "loves", "calls", "upholds"],
    ref: "Philippians 4:13" },

  /* ---------------- Colossians ---------------- */
  { src: "Colossians", type: "fill",
    q: "“He is the ____ of the invisible God, the first-born of all creation.”",
    choices: ["image", "glory", "voice", "wisdom"],
    ref: "Colossians 1:15" },
  { src: "Colossians", type: "conceptual",
    q: "According to Colossians, what dwells in Christ bodily?",
    choices: ["The whole fullness of deity", "The wisdom of Solomon", "The law and the prophets", "The spirit of Elijah"],
    ref: "Colossians 2:9" },

  /* ---------------- 1 Thessalonians ---------------- */
  { src: "1 Thessalonians", type: "fill",
    q: "“Rejoice always, pray without ____, give thanks in all circumstances.”",
    choices: ["ceasing", "doubting", "fear", "words"],
    ref: "1 Thessalonians 5:16–18" },
  { src: "1 Thessalonians", type: "conceptual",
    q: "What event does Paul describe with the words “the Lord himself will descend from heaven with a cry of command… and the dead in Christ will rise first”?",
    choices: ["The second coming of Christ", "Pentecost", "The destruction of the temple", "The conversion of the Gentiles"],
    ref: "1 Thessalonians 4:16" },

  /* ---------------- 2 Thessalonians ---------------- */
  { src: "2 Thessalonians", type: "fill",
    q: "“If any one will not work, let him not ____.”",
    choices: ["eat", "rest", "speak", "complain"],
    ref: "2 Thessalonians 3:10" },
  { src: "2 Thessalonians", type: "conceptual",
    q: "Paul teaches that the day of the Lord will not come until the rebellion comes first and who is revealed?",
    choices: ["The man of lawlessness", "The false prophet", "The beast of the sea", "The king of the north"],
    ref: "2 Thessalonians 2:3" },

  /* ---------------- 1 Timothy ---------------- */
  { src: "1 Timothy", type: "fill",
    q: "Paul calls the church of the living God “the pillar and bulwark of the ____.”",
    choices: ["truth", "faith", "gospel", "covenant"],
    ref: "1 Timothy 3:15" },
  { src: "1 Timothy", type: "fill",
    q: "“There is one God, and there is one ____ between God and men, the man Christ Jesus.”",
    choices: ["mediator", "advocate", "priest", "covenant"],
    ref: "1 Timothy 2:5" },

  /* ---------------- 2 Timothy ---------------- */
  { src: "2 Timothy", type: "fill",
    q: "“All scripture is ____ by God and profitable for teaching, for reproof, for correction, and for training in righteousness.”",
    choices: ["inspired", "written", "blessed", "spoken"],
    ref: "2 Timothy 3:16" },
  { src: "2 Timothy", type: "fill",
    q: "“I have fought the good fight, I have finished the race, I have kept the ____.”",
    choices: ["faith", "law", "watch", "promise"],
    ref: "2 Timothy 4:7" },

  /* ---------------- Titus ---------------- */
  { src: "Titus", type: "conceptual",
    q: "On which island did Paul leave Titus, to “appoint elders in every town”?",
    choices: ["Crete", "Cyprus", "Malta", "Patmos"],
    ref: "Titus 1:5" },
  { src: "Titus", type: "conceptual",
    q: "Titus 3:5 — God “saved us… by the washing of regeneration and renewal in the Holy Spirit” — is read by the Church as describing which sacrament?",
    choices: ["Baptism", "Confirmation", "Penance", "Anointing of the Sick"],
    ref: "Titus 3:5; CCC 1215" },

  /* ---------------- Philemon ---------------- */
  { src: "Philemon", type: "conceptual",
    q: "Paul wrote his shortest letter to Philemon appealing on behalf of whom?",
    choices: ["Onesimus, a runaway slave", "Timothy, his young disciple", "Epaphras, a fellow prisoner", "Demas, who had deserted him"],
    ref: "Philemon 10–16" },
  { src: "Philemon", type: "conceptual",
    q: "How does Paul ask Philemon to receive Onesimus back?",
    choices: ["No longer as a slave, but as a beloved brother", "As a hired servant", "As a debtor to be forgiven", "As a messenger of the church"],
    ref: "Philemon 16" },

  /* ---------------- Hebrews ---------------- */
  { src: "Hebrews", type: "conceptual",
    q: "According to Hebrews, Jesus is a high priest forever after the order of whom?",
    choices: ["Melchizedek", "Aaron", "Levi", "Zadok"],
    ref: "Hebrews 7:17" },
  { src: "Hebrews", type: "fill",
    q: "“Faith is the assurance of things ____ for, the conviction of things not seen.”",
    choices: ["hoped", "prayed", "longed", "asked"],
    ref: "Hebrews 11:1" },

  /* ---------------- James ---------------- */
  { src: "James", type: "fill",
    q: "“For as the body apart from the spirit is dead, so faith apart from ____ is dead.”",
    choices: ["works", "love", "prayer", "hope"],
    ref: "James 2:26" },
  { src: "James", type: "conceptual",
    q: "James 5:14 — “Is any among you sick? Let him call for the elders of the church, and let them pray over him, anointing him with oil” — is a scriptural root of which sacrament?",
    choices: ["Anointing of the Sick", "Confirmation", "Penance", "Holy Orders"],
    ref: "James 5:14–15; CCC 1510" },

  /* ---------------- 1 Peter ---------------- */
  { src: "1 Peter", type: "fill",
    q: "“You are a chosen race, a royal ____, a holy nation, God's own people.”",
    choices: ["priesthood", "family", "remnant", "assembly"],
    ref: "1 Peter 2:9" },
  { src: "1 Peter", type: "fill",
    q: "“Always be prepared to make a defense to any one who calls you to account for the ____ that is in you.”",
    choices: ["hope", "faith", "truth", "light"],
    ref: "1 Peter 3:15" },
  { src: "1 Peter", type: "conceptual",
    q: "Peter teaches that the flood-waters of Noah's day prefigured what, “which now saves you”?",
    choices: ["Baptism", "The Eucharist", "Repentance", "Martyrdom"],
    ref: "1 Peter 3:20–21" },

  /* ---------------- 2 Peter ---------------- */
  { src: "2 Peter", type: "fill",
    q: "Through God's promises we may “become partakers of the divine ____.”",
    choices: ["nature", "glory", "kingdom", "wisdom"],
    ref: "2 Peter 1:4" },
  { src: "2 Peter", type: "fill",
    q: "“With the Lord one day is as a thousand ____, and a thousand ____ as one day.”",
    choices: ["years", "ages", "nights", "generations"],
    ref: "2 Peter 3:8" },

  /* ---------------- 1 John ---------------- */
  { src: "1 John", type: "fill",
    q: "“He who does not love does not know God; for God is ____.”",
    choices: ["love", "light", "truth", "spirit"],
    ref: "1 John 4:8" },
  { src: "1 John", type: "fill",
    q: "“If we ____ our sins, he is faithful and just, and will forgive our sins.”",
    choices: ["confess", "regret", "hide", "remember"],
    ref: "1 John 1:9" },
  { src: "1 John", type: "conceptual",
    q: "According to 1 John, who is “the liar” and “the antichrist”?",
    choices: ["He who denies that Jesus is the Christ", "He who breaks the sabbath", "He who loves the world", "He who judges his brother"],
    ref: "1 John 2:22" },

  /* ---------------- 2 John ---------------- */
  { src: "2 John", type: "conceptual",
    q: "To whom is the Second Letter of John addressed?",
    choices: ["“The elect lady and her children” — understood as a local church", "The seven churches of Asia", "Gaius the beloved", "The twelve tribes in the Dispersion"],
    ref: "2 John 1" },
  { src: "2 John", type: "conceptual",
    q: "2 John warns against deceivers who will not acknowledge what?",
    choices: ["The coming of Jesus Christ in the flesh", "The authority of the apostles", "The resurrection of the dead", "The day of judgment"],
    ref: "2 John 7" },

  /* ---------------- 3 John ---------------- */
  { src: "3 John", type: "conceptual",
    q: "To whom is the Third Letter of John addressed?",
    choices: ["Gaius", "Philemon", "Diotrephes", "Demetrius"],
    ref: "3 John 1" },
  { src: "3 John", type: "conceptual",
    q: "What practice toward traveling missionaries does 3 John commend?",
    choices: ["Hospitality — supporting them “as befits God's service”", "Testing their prophecies", "Sending them away in peace", "Anointing them with oil"],
    ref: "3 John 5–8" },

  /* ---------------- Jude ---------------- */
  { src: "Jude", type: "fill",
    q: "Jude urges believers “to ____ for the faith which was once for all delivered to the saints.”",
    choices: ["contend", "watch", "hope", "labor"],
    ref: "Jude 3" },
  { src: "Jude", type: "conceptual",
    q: "Jude recounts which archangel contending with the devil over the body of Moses?",
    choices: ["Michael", "Gabriel", "Raphael", "Uriel"],
    ref: "Jude 9" },

  /* ---------------- Revelation ---------------- */
  { src: "Revelation", type: "conceptual",
    q: "On which island was John when he received the visions of Revelation?",
    choices: ["Patmos", "Cyprus", "Crete", "Malta"],
    ref: "Revelation 1:9" },
  { src: "Revelation", type: "fill",
    q: "“I am the Alpha and the ____, the first and the last, the beginning and the end.”",
    choices: ["Omega", "Amen", "Almighty", "Morning Star"],
    ref: "Revelation 22:13" },
  { src: "Revelation", type: "conceptual",
    q: "In Revelation 12, who appears “clothed with the sun, with the moon under her feet, and on her head a crown of twelve stars”?",
    choices: ["A woman (seen by the Church as Mary and Israel/the Church)", "The bride of the Lamb", "The angel of the church of Ephesus", "Wisdom personified"],
    ref: "Revelation 12:1" },

  /* ============================================================
     CATECHISM OF THE CATHOLIC CHURCH
     ============================================================ */

  /* ------- Part I, Section 1: Revelation, Scripture & Faith ------- */
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "fill",
    q: "“The desire for God is written in the human ____, because man is created by God and for God.”",
    choices: ["heart", "soul", "mind", "conscience"],
    ref: "CCC 27" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "fill",
    q: "“Faith is man's ____ to God, who reveals himself and gives himself to man.”",
    choices: ["response", "debt", "journey", "surrender"],
    ref: "CCC 26" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "conceptual",
    q: "How many books make up the Catholic canon of Sacred Scripture?",
    choices: ["73 — 46 in the Old Testament and 27 in the New", "66 — 39 in the Old Testament and 27 in the New", "72 — 45 in the Old Testament and 27 in the New", "70 — 43 in the Old Testament and 27 in the New"],
    ref: "CCC 120" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "conceptual",
    q: "Together, what two realities “make up a single sacred deposit of the Word of God”?",
    choices: ["Sacred Scripture and Sacred Tradition", "The Old and New Testaments", "The Creed and the sacraments", "The Law and the Prophets"],
    ref: "CCC 97" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "conceptual",
    q: "To whom has the task of authentically interpreting the Word of God been entrusted?",
    choices: ["The Magisterium — the bishops in communion with the Pope", "Each individual believer", "The theologians of the universities", "The monastic orders"],
    ref: "CCC 85" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "fill",
    q: "St. Jerome: “Ignorance of the Scriptures is ignorance of ____.”",
    choices: ["Christ", "God", "salvation", "the faith"],
    ref: "CCC 133" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "conceptual",
    q: "Which books hold a unique place in the Church, “because they are our principal source for the life and teaching” of Jesus?",
    choices: ["The four Gospels", "The letters of Paul", "The Psalms", "The books of Moses"],
    ref: "CCC 125" },
  { src: "CCC Part I — Revelation, Scripture & Faith", type: "conceptual",
    q: "According to an ancient tradition, what are the two senses of Scripture?",
    choices: ["The literal and the spiritual", "The historical and the poetic", "The public and the hidden", "The prophetic and the moral"],
    ref: "CCC 115" },

  /* ------- Part I, Section 2: The Creed ------- */
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What is the central mystery of the Christian faith and life?",
    choices: ["The mystery of the Most Holy Trinity", "The Incarnation", "The Resurrection", "The Immaculate Conception"],
    ref: "CCC 234" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What are the four marks of the Church professed in the Creed?",
    choices: ["One, holy, catholic, and apostolic", "Holy, Roman, catholic, and universal", "One, faithful, apostolic, and eternal", "Visible, holy, universal, and missionary"],
    ref: "CCC 811" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What does the word “catholic” mean?",
    choices: ["Universal", "Holy", "Roman", "Chosen"],
    ref: "CCC 830" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What does the dogma of the Immaculate Conception teach?",
    choices: ["Mary was preserved from original sin from the first moment of her conception", "Jesus was conceived by the Holy Spirit", "Mary remained a virgin her whole life", "Mary was assumed body and soul into heaven"],
    ref: "CCC 491" },
  { src: "CCC Part I — The Creed", type: "fill",
    q: "“Man is created in the ____ and likeness of God.”",
    choices: ["image", "spirit", "wisdom", "glory"],
    ref: "CCC 355; Genesis 1:27" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "According to the Catechism, the human person, made in the image of God, is a being at once corporeal and what?",
    choices: ["Spiritual", "Immortal", "Rational", "Social"],
    ref: "CCC 362" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What is Purgatory?",
    choices: ["The final purification of the elect, so as to achieve the holiness necessary to enter heaven", "A second chance for the damned", "The waiting place of the just before Christ's coming", "A state of eternal separation from God"],
    ref: "CCC 1030–1031" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "The “communion of saints” includes the faithful in which three states?",
    choices: ["Pilgrims on earth, the dead being purified, and the blessed in heaven", "Priests, religious, and laity", "Martyrs, confessors, and virgins", "The baptized, the catechumens, and the angels"],
    ref: "CCC 954" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "From infancy to death, human life is surrounded by the watchful care and intercession of whom?",
    choices: ["The angels (each person has a guardian angel)", "The patriarchs", "The souls in purgatory", "The apostles"],
    ref: "CCC 336" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "The Church confesses that Jesus Christ is “true God and true man.” What is this belief called?",
    choices: ["The mystery of the Incarnation", "The Paschal mystery", "The Transfiguration", "The divine economy"],
    ref: "CCC 464" },
  { src: "CCC Part I — The Creed", type: "conceptual",
    q: "What does the Creed's “resurrection of the body” mean?",
    choices: ["That God will give incorruptible life to our bodies, reunited with our souls, at the last day", "That the soul alone lives forever", "That the saints appear on earth after death", "That we will receive entirely new, unrelated bodies"],
    ref: "CCC 990, 997–1001" },

  /* ------- Part II, Section 1: The Sacred Liturgy ------- */
  { src: "CCC Part II — The Sacred Liturgy", type: "conceptual",
    q: "What does the word “liturgy” originally mean?",
    choices: ["A “public work” — a service in the name of and on behalf of the people", "A sacred meal", "A hymn of praise", "The reading of the law"],
    ref: "CCC 1069" },
  { src: "CCC Part II — The Sacred Liturgy", type: "fill",
    q: "“The sacraments are efficacious ____ of grace, instituted by Christ and entrusted to the Church.”",
    choices: ["signs", "channels", "promises", "works"],
    ref: "CCC 1131" },
  { src: "CCC Part II — The Sacred Liturgy", type: "conceptual",
    q: "Why does the Church celebrate Sunday as “the Lord's Day”?",
    choices: ["It is the day of Christ's Resurrection", "It was the Jewish sabbath", "It was the day of Pentecost", "The apostles chose it by lot"],
    ref: "CCC 1166, 2174" },
  { src: "CCC Part II — The Sacred Liturgy", type: "conceptual",
    q: "With which season does the Church's liturgical year begin?",
    choices: ["Advent", "Lent", "Ordinary Time", "Christmas"],
    ref: "cf. CCC 524" },
  { src: "CCC Part II — The Sacred Liturgy", type: "fill",
    q: "Easter is not simply one feast among others, but the “Feast of feasts,” the “Solemnity of solemnities,” as the Eucharist is the “Sacrament of ____.”",
    choices: ["sacraments", "salvation", "the Church", "unity"],
    ref: "CCC 1169" },

  /* ------- Part II, Section 2: The Seven Sacraments ------- */
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "How many sacraments did Christ institute and entrust to the Church?",
    choices: ["Seven", "Three", "Ten", "Twelve"],
    ref: "CCC 1113" },
  { src: "CCC Part II — The Seven Sacraments", type: "fill",
    q: "“The Eucharist is the source and ____ of the Christian life.”",
    choices: ["summit", "center", "sign", "seal"],
    ref: "CCC 1324" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "Which three sacraments are the sacraments of Christian initiation?",
    choices: ["Baptism, Confirmation, and the Eucharist", "Baptism, Penance, and the Eucharist", "Baptism, Confirmation, and Matrimony", "Baptism, the Eucharist, and Holy Orders"],
    ref: "CCC 1212" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "By what term does the Church describe the change of the bread and wine into the Body and Blood of Christ?",
    choices: ["Transubstantiation", "Consubstantiation", "Transfiguration", "Sanctification"],
    ref: "CCC 1376" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "What does Baptism forgive?",
    choices: ["Original sin and all personal sins", "Original sin only", "Venial sins only", "Sins committed after the age of reason"],
    ref: "CCC 1263" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "Which two sacraments are called the sacraments of healing?",
    choices: ["Penance and the Anointing of the Sick", "Baptism and Penance", "The Eucharist and the Anointing of the Sick", "Penance and the Eucharist"],
    ref: "CCC 1421" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "Which two sacraments are directed toward the salvation of others and are called sacraments at the service of communion?",
    choices: ["Holy Orders and Matrimony", "Confirmation and Matrimony", "Holy Orders and the Eucharist", "Baptism and Confirmation"],
    ref: "CCC 1534" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "With what is a Christian anointed in Confirmation?",
    choices: ["Sacred chrism", "The oil of catechumens", "The oil of the sick", "Blessed water"],
    ref: "CCC 1289, 1300" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "In the Latin rite, who is the ordinary minister of Confirmation?",
    choices: ["The bishop", "The pastor", "Any priest", "The deacon"],
    ref: "CCC 1313" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "In the Latin Church, who are the ministers of the sacrament of Matrimony?",
    choices: ["The spouses themselves, who confer it on each other", "The priest who witnesses the vows", "The bishop of the diocese", "The parents of the couple"],
    ref: "CCC 1623" },
  { src: "CCC Part II — The Seven Sacraments", type: "conceptual",
    q: "What are the three degrees of the sacrament of Holy Orders?",
    choices: ["Bishop, priest, and deacon", "Pope, cardinal, and bishop", "Priest, monk, and friar", "Deacon, acolyte, and lector"],
    ref: "CCC 1536, 1554" },

  /* ------- Part III, Section 1: Life in the Spirit ------- */
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "What three conditions must be met together for a sin to be mortal?",
    choices: ["Grave matter, full knowledge, and deliberate consent", "Grave matter, public scandal, and repetition", "Full knowledge, malice, and obstinacy", "Deliberate consent, grave harm, and lack of repentance"],
    ref: "CCC 1857" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "What are the three theological virtues?",
    choices: ["Faith, hope, and charity", "Prudence, justice, and temperance", "Faith, humility, and obedience", "Hope, mercy, and charity"],
    ref: "CCC 1813" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "What are the four cardinal virtues?",
    choices: ["Prudence, justice, fortitude, and temperance", "Faith, hope, charity, and prudence", "Wisdom, courage, patience, and justice", "Humility, chastity, diligence, and charity"],
    ref: "CCC 1805" },
  { src: "CCC Part III — Life in the Spirit", type: "fill",
    q: "“Conscience is man's most secret core and his ____. There he is alone with God, whose voice echoes in his depths.”",
    choices: ["sanctuary", "refuge", "judge", "compass"],
    ref: "CCC 1776" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "How many capital sins does the Church's tradition name?",
    choices: ["Seven", "Ten", "Three", "Twelve"],
    ref: "CCC 1866" },
  { src: "CCC Part III — Life in the Spirit", type: "fill",
    q: "“Grace is favor, the free and ____ help that God gives us to respond to his call.”",
    choices: ["undeserved", "abundant", "hidden", "sanctifying"],
    ref: "CCC 1996" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "The first precept of the Church requires the faithful to do what?",
    choices: ["Attend Mass on Sundays and holy days of obligation", "Fast every Friday of the year", "Confess their sins once a month", "Tithe ten percent of their income"],
    ref: "CCC 2042" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "How many Beatitudes does Jesus proclaim in the Sermon on the Mount?",
    choices: ["Eight", "Seven", "Ten", "Twelve"],
    ref: "CCC 1716; Matthew 5:3–10" },
  { src: "CCC Part III — Life in the Spirit", type: "fill",
    q: "“Sin is an offense against reason, truth, and right ____.”",
    choices: ["conscience", "judgment", "order", "worship"],
    ref: "CCC 1849" },
  { src: "CCC Part III — Life in the Spirit", type: "conceptual",
    q: "What is a venial sin?",
    choices: ["A sin that wounds charity but does not destroy it, leaving sanctifying grace intact", "Any sin committed in ignorance", "A sin forgiven without confession", "A sin against the fifth commandment"],
    ref: "CCC 1863" },

  /* ------- Part III, Section 2: The Ten Commandments ------- */
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "What does the word “Decalogue” mean literally?",
    choices: ["“Ten words”", "“Ten laws”", "“The two tablets”", "“The teaching”"],
    ref: "CCC 2056" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "The first three commandments concern love of God; what do the other seven concern?",
    choices: ["Love of neighbor", "Worship in the temple", "The duties of kings", "Ritual purity"],
    ref: "CCC 2067" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "Which commandment does the Sunday obligation to attend Mass flow from?",
    choices: ["The third — “Remember to keep holy the Lord's day”", "The first — “You shall have no other gods”", "The fourth — “Honor your father and your mother”", "The second — “You shall not take the name of the LORD in vain”"],
    ref: "CCC 2168, 2180" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "What does the second commandment forbid?",
    choices: ["The abuse of God's name — blasphemy, false oaths, and irreverence", "Work on the sabbath", "The making of images of any kind", "Speaking of God to unbelievers"],
    ref: "CCC 2142–2146" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "Which commandment requires us to honor our father and our mother?",
    choices: ["The fourth", "The first", "The sixth", "The eighth"],
    ref: "CCC 2197" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "On what truth is the fifth commandment, “You shall not kill,” grounded?",
    choices: ["Human life is sacred, because from its beginning it involves the creative action of God", "The state alone may judge offenders", "Bloodshed defiles the land of Israel", "All violence is forbidden to believers"],
    ref: "CCC 2258" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "The seventh commandment, “You shall not steal,” enjoins what in the care of earthly goods?",
    choices: ["Justice and charity, and respect for the goods of others", "The renunciation of all property", "Equal wealth for all persons", "The payment of temple taxes"],
    ref: "CCC 2401" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "What does the eighth commandment forbid?",
    choices: ["Misrepresenting the truth — false witness, lying, and calumny", "Envy of a neighbor's goods", "Swearing any oath at all", "Judging one's own conscience"],
    ref: "CCC 2464" },
  { src: "CCC Part III — The Ten Commandments", type: "conceptual",
    q: "What do the ninth and tenth commandments forbid?",
    choices: ["Covetous desires — of the flesh and of another's goods", "Idolatry and superstition", "Theft and fraud", "False oaths and perjury"],
    ref: "CCC 2514, 2534" },

  /* ------- Part IV, Section 1: Prayer in the Christian Life ------- */
  { src: "CCC Part IV — Prayer in the Christian Life", type: "fill",
    q: "St. John Damascene: “Prayer is the raising of one's mind and heart to ____ or the requesting of good things from God.”",
    choices: ["God", "heaven", "the Father", "Christ"],
    ref: "CCC 2559" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "fill",
    q: "St. Thérèse of Lisieux: “For me, prayer is a surge of the ____; it is a simple look turned toward heaven.”",
    choices: ["heart", "soul", "spirit", "will"],
    ref: "CCC 2558" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "conceptual",
    q: "What are the three major expressions of the life of prayer?",
    choices: ["Vocal prayer, meditation, and contemplative prayer", "Petition, praise, and thanksgiving", "Liturgy, devotion, and silence", "Adoration, intercession, and blessing"],
    ref: "CCC 2699" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "conceptual",
    q: "Which forms of prayer does the Catechism name, alongside petition and intercession?",
    choices: ["Blessing and adoration, thanksgiving, and praise", "Fasting, vigils, and almsgiving", "Lament, confession, and vows", "Silence, song, and pilgrimage"],
    ref: "CCC 2626–2643" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "conceptual",
    q: "What are the two habitual difficulties in the “battle of prayer” named by the Catechism?",
    choices: ["Distraction and dryness", "Doubt and despair", "Fatigue and fear", "Pride and impatience"],
    ref: "CCC 2729–2731" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "conceptual",
    q: "Whom does the Catechism present as the perfect “Orans” — a pure figure of the Church at prayer?",
    choices: ["The Virgin Mary", "St. John the Baptist", "King David", "St. Paul"],
    ref: "CCC 2679" },
  { src: "CCC Part IV — Prayer in the Christian Life", type: "conceptual",
    q: "Which Old Testament book does the Catechism call “the masterwork of prayer in the Old Testament”?",
    choices: ["The Psalms", "The Song of Songs", "Lamentations", "The prayers of Daniel"],
    ref: "CCC 2585" },

  /* ------- Part IV, Section 2: The Lord's Prayer ------- */
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "How many petitions does the Our Father contain?",
    choices: ["Seven", "Five", "Ten", "Three"],
    ref: "CCC 2803" },
  { src: "CCC Part IV — The Lord's Prayer", type: "fill",
    q: "Tertullian: “The Lord's Prayer is truly the summary of the whole ____.”",
    choices: ["gospel", "law", "faith", "Scripture"],
    ref: "CCC 2761" },
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "Jesus taught His disciples the Our Father when they asked Him what?",
    choices: ["“Lord, teach us to pray”", "“Lord, increase our faith”", "“Lord, show us the Father”", "“Lord, to whom shall we go?”"],
    ref: "CCC 2759; Luke 11:1" },
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "The word “Abba,” with which Jesus addressed God, means what?",
    choices: ["Father", "Lord", "Master", "Holy One"],
    ref: "CCC 2766; Mark 14:36" },
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "In the petition “Give us this day our daily bread,” the Church reads “daily bread” as referring also to what?",
    choices: ["The Eucharist, the Bread of Life", "The manna in the desert", "The word of Scripture alone", "Earthly prosperity"],
    ref: "CCC 2837" },
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "What does the final “Amen” of the Lord's Prayer mean?",
    choices: ["“So be it”", "“Have mercy”", "“Praise God”", "“Come, Lord”"],
    ref: "CCC 2856" },
  { src: "CCC Part IV — The Lord's Prayer", type: "conceptual",
    q: "In the petition “deliver us from evil,” to whom does “evil” refer?",
    choices: ["The Evil One — Satan, the angel who opposes God", "Natural disasters", "Human weakness in general", "The sufferings of this life"],
    ref: "CCC 2851" },

  /* ============================================================
     SAINTS THROUGH THE AGES
     ============================================================ */

  /* ------- The Apostolic Age (1st century) ------- */
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "According to ancient tradition, how was St. Peter martyred in Rome?",
    choices: ["Crucified upside down, counting himself unworthy to die as his Lord", "Beheaded by the sword", "Thrown to the lions", "Stoned outside the city walls"],
    ref: "Tradition; cf. John 21:18–19" },
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "Why was St. Paul beheaded rather than crucified?",
    choices: ["He was a Roman citizen", "He was too old for crucifixion", "The emperor pardoned him first", "He died before sentence was carried out"],
    ref: "Tradition; cf. Acts 22:25–28" },
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "Which saint, the first witness of the Resurrection, is honored as the “Apostle to the Apostles”?",
    choices: ["St. Mary Magdalene", "St. Martha", "St. Salome", "St. Joanna"],
    ref: "John 20:11–18" },
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "Which apostle, according to tradition, was not martyred but died in old age at Ephesus?",
    choices: ["St. John", "St. James the Greater", "St. Thomas", "St. Bartholomew"],
    ref: "Early tradition (Irenaeus, Eusebius)" },
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "The foster-father of Jesus is honored as patron of the universal Church. Who is he?",
    choices: ["St. Joseph", "St. Joachim", "St. Zechariah", "St. John the Baptist"],
    ref: "Pius IX, Quemadmodum Deus (1870)" },
  { src: "Saints — The Apostolic Age (1st century)", type: "conceptual",
    q: "Which apostle is traditionally said to have been martyred on an X-shaped cross?",
    choices: ["St. Andrew", "St. Philip", "St. Matthias", "St. Simon the Zealot"],
    ref: "Tradition; the “saltire” cross" },

  /* ------- The Early Church (2nd–5th centuries) ------- */
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "Which bishop and martyr wrote seven letters on his way to execution in Rome, giving us the earliest recorded use of the phrase “the Catholic Church”?",
    choices: ["St. Ignatius of Antioch", "St. Clement of Rome", "St. Justin Martyr", "St. Irenaeus of Lyons"],
    ref: "Letter to the Smyrnaeans 8 (c. 107)" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "St. Polycarp, martyred at age 86, was bishop of Smyrna and a disciple of which apostle?",
    choices: ["St. John", "St. Peter", "St. Paul", "St. James"],
    ref: "Martyrdom of Polycarp; Irenaeus" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "Sts. Perpetua and Felicity, a young noblewoman and her servant, were martyred together in which city?",
    choices: ["Carthage", "Rome", "Alexandria", "Antioch"],
    ref: "The Passion of Perpetua and Felicity (203)" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "St. Athanasius of Alexandria spent his life — and five exiles — defending which truth?",
    choices: ["The full divinity of Christ, against the Arian heresy", "The authority of the Pope", "The perpetual virginity of Mary", "The canon of Scripture"],
    ref: "Council of Nicaea (325)" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "Which saint translated the Bible into Latin, producing the Vulgate?",
    choices: ["St. Jerome", "St. Augustine", "St. Ambrose", "St. Gregory the Great"],
    ref: "St. Jerome (d. 420)" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "Which saint prayed with tears for many years for the conversion of her son, the future St. Augustine?",
    choices: ["St. Monica", "St. Helena", "St. Paula", "St. Macrina"],
    ref: "Augustine, Confessions IX" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "fill",
    q: "St. Augustine: “You have made us for yourself, O Lord, and our heart is restless until it rests in ____.”",
    choices: ["you", "heaven", "peace", "truth"],
    ref: "Confessions I,1" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "According to beloved tradition, St. Patrick used what to teach the Irish about the Holy Trinity?",
    choices: ["A shamrock", "A triple knot", "Three candles", "A three-leafed olive branch"],
    ref: "Tradition; St. Patrick, Apostle of Ireland (5th c.)" },
  { src: "Saints — The Early Church (2nd–5th centuries)", type: "conceptual",
    q: "Which 4th-century bishop of Myra, famous for secret gift-giving, lives on in legend as “Santa Claus”?",
    choices: ["St. Nicholas", "St. Basil", "St. Blaise", "St. Valentine"],
    ref: "St. Nicholas of Myra (d. c. 343)" },

  /* ------- The Middle Ages (6th–15th centuries) ------- */
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Who is called the father of Western monasticism, whose Rule shaped religious life for centuries?",
    choices: ["St. Benedict of Nursia", "St. Bernard of Clairvaux", "St. Columba", "St. Bruno"],
    ref: "Rule of St. Benedict (6th c.)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "fill",
    q: "The Benedictine motto: “Ora et ____” — “pray and work.”",
    choices: ["labora", "vigila", "credo", "ama"],
    ref: "Benedictine tradition" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Which brother saints, “Apostles to the Slavs,” devised an alphabet to bring the Gospel and the liturgy to the Slavic peoples?",
    choices: ["Sts. Cyril and Methodius", "Sts. Cosmas and Damian", "Sts. Boris and Gleb", "Sts. Crispin and Crispinian"],
    ref: "9th century; co-patrons of Europe" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Which saint embraced “Lady Poverty,” founded the Friars Minor, and received the stigmata on Mount La Verna?",
    choices: ["St. Francis of Assisi", "St. Dominic", "St. Bonaventure", "St. Bernardine of Siena"],
    ref: "St. Francis of Assisi (1181–1226)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "St. Clare of Assisi, friend and follower of St. Francis, founded which order of contemplative nuns?",
    choices: ["The Poor Clares", "The Carmelites", "The Visitation Sisters", "The Bridgettines"],
    ref: "St. Clare (1194–1253)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "St. Dominic founded which order, dedicated to preaching and long associated with the Rosary?",
    choices: ["The Order of Preachers (Dominicans)", "The Franciscans", "The Augustinians", "The Cistercians"],
    ref: "St. Dominic (1170–1221)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Which Franciscan preacher, wonder-worker of Padua, is popularly invoked to find lost things?",
    choices: ["St. Anthony of Padua", "St. Louis of Toulouse", "St. Leopold", "St. Albert the Great"],
    ref: "St. Anthony of Padua (1195–1231)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "The “Angelic Doctor,” author of the Summa Theologiae, is which Dominican saint?",
    choices: ["St. Thomas Aquinas", "St. Albert the Great", "St. Anselm", "St. Bonaventure"],
    ref: "St. Thomas Aquinas (1225–1274)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Which Doctor of the Church persuaded Pope Gregory XI to leave Avignon and return to Rome?",
    choices: ["St. Catherine of Siena", "St. Bridget of Sweden", "St. Hildegard of Bingen", "St. Angela of Foligno"],
    ref: "St. Catherine of Siena (1347–1380)" },
  { src: "Saints — The Middle Ages (6th–15th centuries)", type: "conceptual",
    q: "Which teenage saint led French armies at Orléans and was burned at the stake at Rouen in 1431?",
    choices: ["St. Joan of Arc", "St. Genevieve", "St. Clotilde", "St. Margaret of Scotland"],
    ref: "St. Joan of Arc (1412–1431)" },

  /* ------- The Age of Reform (16th–17th centuries) ------- */
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which wounded soldier, converted while reading the lives of the saints, founded the Society of Jesus and wrote the Spiritual Exercises?",
    choices: ["St. Ignatius of Loyola", "St. Francis Borgia", "St. John of God", "St. Camillus de Lellis"],
    ref: "St. Ignatius of Loyola (1491–1556)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which Jesuit, patron of missions, carried the Gospel to India and Japan?",
    choices: ["St. Francis Xavier", "St. Peter Claver", "St. Isaac Jogues", "St. Aloysius Gonzaga"],
    ref: "St. Francis Xavier (1506–1552)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which Spanish mystic reformed the Carmelite order and wrote The Interior Castle?",
    choices: ["St. Teresa of Ávila", "St. Rose of Lima", "St. Margaret Mary Alacoque", "St. Louise de Marillac"],
    ref: "St. Teresa of Ávila (1515–1582)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which Carmelite friar and poet, co-worker of St. Teresa, wrote of the “dark night of the soul”?",
    choices: ["St. John of the Cross", "St. John of Ávila", "St. Peter of Alcántara", "St. Philip Neri"],
    ref: "St. John of the Cross (1542–1591)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "fill",
    q: "St. Thomas More, Chancellor of England, died on the scaffold declaring himself “the King's good servant, but God's ____.”",
    choices: ["first", "own", "friend", "witness"],
    ref: "St. Thomas More, martyred 1535" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which cheerful saint, called the “Apostle of Rome,” founded the Oratory?",
    choices: ["St. Philip Neri", "St. Charles Borromeo", "St. Robert Bellarmine", "St. Cajetan"],
    ref: "St. Philip Neri (1515–1595)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which gentle bishop of Geneva wrote the Introduction to the Devout Life and is patron of writers and journalists?",
    choices: ["St. Francis de Sales", "St. Vincent de Paul", "St. Alphonsus Liguori", "St. John Bosco"],
    ref: "St. Francis de Sales (1567–1622)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "On whose tilma did Our Lady of Guadalupe leave her miraculous image in 1531?",
    choices: ["St. Juan Diego", "St. Martín de Porres", "St. Felipe de Jesús", "St. Toribio of Mogrovejo"],
    ref: "Guadalupe, 1531; canonized 2002" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which young Mohawk woman, the “Lily of the Mohawks,” became the first Native American to be canonized?",
    choices: ["St. Kateri Tekakwitha", "St. Rose Philippine Duchesne", "St. Marianne Cope", "St. Josephine Bakhita"],
    ref: "St. Kateri Tekakwitha (1656–1680)" },
  { src: "Saints — The Age of Reform (16th–17th centuries)", type: "conceptual",
    q: "Which French priest organized vast works of charity, giving his name to a worldwide society serving the poor?",
    choices: ["St. Vincent de Paul", "St. Louis de Montfort", "St. John Eudes", "St. Claude de la Colombière"],
    ref: "St. Vincent de Paul (1581–1660)" },

  /* ------- The Modern Era (18th–21st centuries) ------- */
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Which young Carmelite, the “Little Flower,” taught the “little way” of confidence and love?",
    choices: ["St. Thérèse of Lisieux", "St. Bernadette Soubirous", "St. Gemma Galgani", "St. Elizabeth of the Trinity"],
    ref: "St. Thérèse of Lisieux (1873–1897)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "To which saint did Our Lady appear at Lourdes, saying “I am the Immaculate Conception”?",
    choices: ["St. Bernadette Soubirous", "St. Catherine Labouré", "St. Jacinta Marto", "St. Mariam Baouardy"],
    ref: "Lourdes, 1858" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "The Curé of Ars, who spent up to sixteen hours a day in the confessional, is the patron of parish priests. Who is he?",
    choices: ["St. John Vianney", "St. John Bosco", "St. Peter Julian Eymard", "St. Pius X"],
    ref: "St. John Vianney (1786–1859)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Who was the first native-born citizen of the United States to be canonized?",
    choices: ["St. Elizabeth Ann Seton", "St. Frances Xavier Cabrini", "St. Katharine Drexel", "St. John Neumann"],
    ref: "St. Elizabeth Ann Seton (1774–1821)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "fill",
    q: "The Divine Mercy image revealed to St. Faustina Kowalska bears the inscription: “Jesus, I ____ in you.”",
    choices: ["trust", "hope", "believe", "rest"],
    ref: "Diary of St. Faustina" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Which Franciscan priest offered his life in place of a fellow prisoner at Auschwitz?",
    choices: ["St. Maximilian Kolbe", "St. Titus Brandsma", "Bl. Michał Kozal", "St. Edith Stein"],
    ref: "St. Maximilian Kolbe (1894–1941)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Which Capuchin friar of Pietrelcina bore the stigmata for fifty years and spent long hours hearing confessions?",
    choices: ["St. Pio of Pietrelcina (Padre Pio)", "St. Leopold Mandić", "St. Charbel Makhlouf", "St. André Bessette"],
    ref: "St. Padre Pio (1887–1968)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Which saint founded the Missionaries of Charity to serve “the poorest of the poor” in Calcutta?",
    choices: ["St. Teresa of Calcutta (Mother Teresa)", "St. Josephine Bakhita", "St. Dulce of the Poor", "St. Jeanne Jugan"],
    ref: "St. Teresa of Calcutta (1910–1997)" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "fill",
    q: "St. John Paul II opened his pontificate with the cry: “Be not ____! Open wide the doors for Christ!”",
    choices: ["afraid", "silent", "ashamed", "weary"],
    ref: "Inaugural homily, October 22, 1978" },
  { src: "Saints — The Modern Era (18th–21st centuries)", type: "conceptual",
    q: "Which teenager, who built a website documenting Eucharistic miracles, became the first millennial to be canonized?",
    choices: ["St. Carlo Acutis", "St. Pier Giorgio Frassati", "St. Dominic Savio", "St. José Sánchez del Río"],
    ref: "St. Carlo Acutis (1991–2006), canonized 2025" },
];
